### ISSUE TITLE
Access Denied saat install 

### ISSUE THREAD

**Issue by httazunyan** [gvoze32/unblockhostid#100]
![screenshot 68](https://user-images.githubusercontent.com/36813666/36640731-0b5ca718-1a57-11e8-9ec5-ac4489db51d3.png)
Tolong saya, Ini saya gunakan untuk membuka Reddit dkk
![image](https://user-images.githubusercontent.com/36813666/36640969-f6f3e0da-1a5a-11e8-9f4c-3f46ef849681.png)

**Comment by gvoze32** [comment]
Habis ngecheat pake pekalongan ya? wkwkwk

Klik kanan hosts asli, terus ubah permissionnya, hapus semua centangnya, terus hapus file hostsnya juga, baru kamu bisa install

**Comment by httazunyan** [comment]
cit pekalongan ngaruh ya ? soalnya adik main nge cit mulu 👍 ✌️ ;:'v
