### ISSUE TITLE
[ID] [BUG] playstore no connection using adaway

### ISSUE THREAD

**Issue by venomobster** [gvoze32/unblockhostid#102]
bang, ini kenapa ya waktu aku install hosts lewat adaway aku gak bisa akses playstore. padahal youtube sama browisng bisa aja.

setelah searching aku ketemu solusinya, katanya hosts file android harus di restore ke original baru bisa pake playstore. setelah aku restore hosts kembali  ke ori lewat adaway., playstore nya sudah bisa diakses lagi. 

kenapa begitu ya bang?

**Comment by venomobster** [comment]
Nambahin, aku pake kartu as 4G, android 5.1.1 sudah rooted

**Comment by gvoze32** [comment]
Mungkin hosts di adawaynya ada yang blokir akses ke play store, unblockhostid gk ngelist play store kok.

**Comment by venomobster** [comment]
Kemarin waktu aku coba install ulang lagi unblockhostid lewat adaway, playstorenya udah bisa dibuka lagi. Jadi kemungkinan bugnya waktu aku install unblockhostid di adaway yg salah atau hpku yg error.

Welp, nothing wrong in your unblockhostid then. Please close this issue and thank you for you respond.
