### ISSUE TITLE
[REQUEST] [ID] https://talk.plesk.com

### ISSUE THREAD

**Issue by fuadhammam** [gvoze32/unblockhostid#103]
bukan situs 18+
cuma forum diskusi masalah plesk ( hosting cpanel )

**Comment by gvoze32** [comment]
Saya cek tidak diblokir
![image](https://user-images.githubusercontent.com/28755051/36787349-70ae3e80-1cbc-11e8-9b8f-d9652900883c.png)

**Comment by fuadhammam** [comment]
ok, closed
