### ISSUE TITLE
[ID][BUG][PC] netflix.com

### ISSUE THREAD

**Issue by arieagung** [gvoze32/unblockhostid#119]
Situs netflix-nya bisa dibuka dan bisa browsing tapi tidak bisa di-play, hanya loading terus.

OS: Win10
Browser: Chrome

**Comment by gvoze32** [comment]
Still have no idea.

**Comment by deckyfx** [comment]
You might need to inspect the requests made to stream the video data.
Biasanya beberapa video host besar menaruh file stream dan website di domain berbeda,

**Comment by andrefsianipar** [comment]
as @deckyfx said. Homepage situs bisa dibuka tapi beberapa konten tidak muncul kemungkinan karena disimpan di subdomain berbeda. Misalnya github punya subdomain https://assets-cdn.github.com. Domain berikut subdomain harus include di hosts

**Comment by gvoze32** [comment]
Tapi saya cari yang diblok cuma homepagenya saja, sisanya tidak
