### ISSUE TITLE
ABOUT NETFLIX (README)

### ISSUE THREAD

**Issue by gvoze32** [gvoze32/unblockhostid#121]
Banyak yang bilang netflix tidak bisa memutar video, tetapi pas saya cek, hanya homepagenya saja yang terkena blokir (netflix.com). Saya berencana untuk melihat/mencari lebih dalam ip/dns media yang mungkin saja kena blokir, hanya saja saya tidak mempunyai akun netflix, jika anda punya anda bisa pm ke saya, nanti akan saya cari problemnya. Saya hanya pinjam, tidak akan saya apa-apakan kok, Terima Kasih.

**Comment by hertahir2** [comment]
ipv4-c027-sin001-ix.1.oca.nflxvideo.net - Singapore
ipv4-c016-sin001-ix.1.oca.nflxvideo.net - Singapore
ipv4-c013-hkg001-ix.1.oca.nflxvideo.net - Hong Kong
ipv4-c017-hkg001-ix.1.oca.nflxvideo.net - Hong Kong
ipv4-c021-tyo001-ix.1.oca.nflxvideo.net - Tokyo

**Comment by gvoze32** [comment]
Saya cek tidak terblokir

**Comment by lepz0r** [comment]
Y paling praktis buat domain yg suka ganti-ganti IP pake Simple DNSCrypt & Semua situs yg diblokir bisa dibuka semua& ga repot repot nambahin ke file host setiap ada situs baru yg diblokir
