### ISSUE TITLE
Terdeteksi sebagai virus

### ISSUE THREAD

**Issue by hertahir2** [gvoze32/unblockhostid#124]
file unblockhostid terdeteksi virus di Windows Defender.
ini diabaikan aja ? (false alarm)
soalnya di Cara Install / Changelog tidak ada keterangan kalau ini false alarm.

<details><summary>SS</summary><p>
<img src=https://user-images.githubusercontent.com/30792774/37565486-578d9450-2ae5-11e8-89a8-318f10a30e81.PNG>
</p>

**Comment by gvoze32** [comment]
False positive gan, memang saya buatnya gak ada keterangan seperti perusahaan, dll dan itu sistemnya replace file/inject, jadi ya wajar kalau dianggap virus. Tapi 100% aman kok.
