### ISSUE TITLE
[ID] [PC] [BUG] nhentai.net

### ISSUE THREAD

**Issue by Chocolalolz** [gvoze32/unblockhostid#126]
mohon segera di fix.
setelah saya otak atik tetep kena internet positif (menggunakkan Unblockhost.id)

**Comment by gvoze32** [comment]
Tested and work like a charm

> ![image](https://user-images.githubusercontent.com/28755051/37696634-bdfd6fb8-2d0a-11e8-9ecb-201cf1336419.png)
