### ISSUE TITLE
[ID] [REQUEST] Walach.co.uk

### ISSUE THREAD

**Issue by gvoze32** [gvoze32/unblockhostid#127]
Sample: walach.co.uk/ktp
> 5.189.166.120 walach.co.uk www.walach.co.uk

**Comment by Macroburst** [comment]
[ID][REQUEST]zonakimochi.top

**Comment by gvoze32** [comment]
@Macroburst 
Itu domainnya gonta-ganti gk?

**Comment by skymunn** [comment]
Itu zonakimochi domainnya gonta ganti, skrg dia jadi zonakimochi.kim

**Comment by gvoze32** [comment]
Kalau gitu gk saya kerjain
