### ISSUE TITLE
[REQUEST] [EXT] tumblr.com

### ISSUE THREAD

**Issue by Ultimateage** [gvoze32/unblockhostid#128]
bang request site 

> tumblr.com

 dan antek-anteknya bang, soalnya di "list of supported sites" sih ada tapi di ane kok kagak bisa dibuka, dan ane pake kartu three bang

> http://31.media.tumblr.com/4f27859f78a35f686bd4ecdc1ae6bf78/tumblr_mqqiwguRUS1rx8bobo1_500.gif

**Comment by gvoze32** [comment]
![image](https://user-images.githubusercontent.com/28755051/37863278-5d602124-2f8e-11e8-9d7f-92f7e22e3ef6.png)

Work like a charm

**Comment by Ultimateage** [comment]
kalo yang site utamanya udah bisa bang, tapi didalemnya ada gambar yg kgk muncul gitu

**Comment by gvoze32** [comment]
Bisa lebih spesifik? Ada link buat samplenya?

**Comment by skymunn** [comment]
![screenshot_492](https://user-images.githubusercontent.com/32958839/37872311-a024ecfc-3037-11e8-8f32-a7fb09a50727.png)

*Ah masa sih?*

**Comment by Ultimateage** [comment]
udah tak sertain contoh kok, kalo kurang jelas ane tulis lagi
http://31.media.tumblr.com/4f27859f78a35f686bd4ecdc1ae6bf78/tumblr_mqqiwguRUS1rx8bobo1_500.gif
kalo dibuka tampil kek gini
![xxxx](https://user-images.githubusercontent.com/34861954/37872511-93a6a014-3033-11e8-8833-826c9bd2cd65.png)

**Comment by gvoze32** [comment]
Coba akses dua link ini, terblokir apa tidak.
78.media.tumblr.com & 31.media.tumblr.com

**Comment by Ultimateage** [comment]
ke block bang

**Comment by gvoze32** [comment]
Berarti provider 3 lebih banyak blokir subdomainnya daripada Telkomsel, nanti saya tambahin ke yang versi Non-ID.
