### ISSUE TITLE
[ID] [BUG] [PC] [MAC] netflix.com

### ISSUE THREAD

**Issue by timedison** [gvoze32/unblockhostid#130]
netflix nya dipakai untuk login bisa tapi video playback tidak jalan, terus kelihatannya sih IP nya netflix yang 35.166.68.183 lemot.

**Comment by gvoze32** [comment]
Semua lemot gan, memang masalahnya Netflix tidak berafiliasi lagi di Indonesia, jadi untuk sekarang aksesnya pakai VPN saja dulu.

**Comment by timedison** [comment]
gan kalo dari web inspector kemaren saya cek ada beberapa link yg klo di ping masuk nya ke IP nya telkom 
36.86.63.182 https://www.netflix.com/api/msl/NFCDSF-01-/cadmium/license
36.86.63.182 https://www.netflix.com/ichnaea/cl2
36.86.63.182 https://www.netflix.com/api/msl/NFCDSF-01-/cadmium/logblob
36.86.63.182 https://www.netflix.com/customerevents/track/debug

sama ada beberapa link lain cuman ga sempet saya cek

<img width="1440" alt="screen shot 2018-03-26 at 22 50 08" src="https://user-images.githubusercontent.com/37805230/37948046-6a046026-31b8-11e8-97c3-6271bb2496e0.png">

cuman sekedar ngecek aja, saya sendiri kurang ngerti

**Comment by gvoze32** [comment]
Itu 36.86.63.182 ip apa? Sama bisa jelasin lebih spesifik link mana saja yang masuk ke ip telkom?

**Comment by timedison** [comment]
link link yang kena error 408 saya ping lewat terminal, yang keluar ip addressnya telkom 36.86.63.182

<img width="653" alt="screen shot 2018-03-27 at 13 30 51" src="https://user-images.githubusercontent.com/37805230/37950598-5afe9ab4-31c3-11e8-8fa2-616feb352fe6.png">

contohnya link:    https://www.netflix.com/ichnaea/cl2

kalau saya ping keluarnya begini

<img width="570" alt="screen shot 2018-03-27 at 13 32 05" src="https://user-images.githubusercontent.com/37805230/37950608-690c993a-31c3-11e8-84d1-7c04120df044.png">

**Comment by gvoze32** [comment]
Wah sepertinya tetep aja gabisa itu gan. Mungkin lain waktu saya cari metode lain.
