### ISSUE TITLE
[ID] [REQUEST] [PC] 4chan.org

### ISSUE THREAD

**Issue by Macroburst** [gvoze32/unblockhostid#136]
di daftar list termasuk site yg disupport, tapi masih internet postif

**Comment by gvoze32** [comment]
![image](https://user-images.githubusercontent.com/28755051/38182816-2e13565a-3666-11e8-83a8-880a7d54d64c.png)
![image](https://user-images.githubusercontent.com/28755051/38182817-33da6678-3666-11e8-8899-07ca5fb3c144.png)

Di saya aman.. Coba clear cache di menu Additional
