### ISSUE TITLE
[PC] tumblr.com no longer work :\

### ISSUE THREAD

**Issue by noegrahachan420** [gvoze32/unblockhostid#137]
I was noticed that bypassing tumblr.com no longer worked since their DNS is changed (?) ~~or they switched into "randomly changed" IP address model~~ hmm wait.... seems they change the IP address

from
`66.6.33.159`

to
`66.6.32.31`

not sure with their assets/resources IP address......
=========
tapi kalau berubah2 IP nya berarti tumblr.com pake sistem IP address yang gonta-ganti tiap waktu seperti facebook dkk

**Comment by gvoze32** [comment]
Ah iya, saya lihat juga berubah, tunggu banyak request dulu ya nanti saya kerjakan.

> 66.6.32.31 tumblr.com www.tumblr.com
