### ISSUE TITLE
[ID] [REQ] imgchili.net

### ISSUE THREAD

**Issue by Macroburst** [gvoze32/unblockhostid#139]

**Comment by gvoze32** [comment]
Data received:

> 104.24.113.61 imgchili.net www.imgchili.net

**Comment by Macroburst** [comment]
kalo untuk game bisa di unblok gak ya? game mobage?

**Comment by gvoze32** [comment]
Bisa.

**Comment by Macroburst** [comment]
oke request nya gimana ya?

**Comment by gvoze32** [comment]
Silahkan open issue dan cantumkan nama gamenya, formatnya sama seperti request biasa.

**Comment by gvoze32** [comment]
Secepatnya.
