### ISSUE TITLE
[ID] [REQ] another soap sites

### ISSUE THREAD

**Issue by Bagus23** [gvoze32/unblockhostid#140]
avcens.download
wetholefans.com
maxjav.com
avgirlblog.me
smalljav.us
biqle.ru
avheat.com
onejav.com
asexon.com
avgle.com
tuoi69.com
dinojav.com
ohyeah1080.com
babepedia.com
celebjihad.com

ini sudah dicek semua pake opera, soalnya kemarin katanya ga boleh request yang belum kena ipochan, makasih ea mamang.

**Comment by gvoze32** [comment]
Data received:

> 104.24.101.246 avcens.download www.avcens.download
> 82.192.82.41 wetholefans.com www. wetholefans.com
> 104.25.60.107 maxjav.com www.maxjav.com
> 104.18.61.22 avgirlblog.me www.avgirlblog.me
> 104.28.10.114 smalljav.us www.smalljav.us
> 104.31.89.145 biqle.ru www.biqle.ru
> 104.24.15.43 avheat.com www.avheat.com
> 104.168.126.14 onejav.com www.onejav.com [INVALID STRING, DELETE OLD LINE]
> 5.44.219.124 asexon.com www.asexon.com
> 104.20.116.27 avgle.com www.avgle.com
> 104.27.178.187 tuoi69.com www.tuoi69.com
> 98.124.204.16 dinojav.com www.dinojav.com
> 104.18.55.5 ohyeah1080.com www.ohyeah1080.com
> 209.188.87.144 babepedia.com www.babepedia.com
> 104.20.137.49 celebjihad.com www.celebjihad.com
