### ISSUE TITLE
[BUG] Kissanime.ru dan kissmanga.com

### ISSUE THREAD

**Issue by shirojishi** [gvoze32/unblockhostid#150]
pada jaringan indihome dan menggunakan firefox beta v60
![screenshot 44](https://user-images.githubusercontent.com/30919296/38991071-ab0c2850-4406-11e8-9370-d791b6e0007b.png)
![screenshot 45](https://user-images.githubusercontent.com/30919296/38991076-aed17972-4406-11e8-882b-39d6dfbd9414.png)

**Comment by Zecx** [comment]
KISSANIME `104.20.26.43 kissanime.ru www.kissanime.ru
KISSMANGA `104.25.45.113 kissmanga.com www.kissmanga.com`
`

![image](https://user-images.githubusercontent.com/37705250/39018061-278ebb66-444f-11e8-899e-c5b246cf6851.png)


make wifi id

![image](https://user-images.githubusercontent.com/37705250/39018140-5ec31406-444f-11e8-9696-4d296766827b.png)

baru gw buka saat ini

![image](https://user-images.githubusercontent.com/37705250/39018163-6b7a72c0-444f-11e8-9275-a3eabdbdf3b0.png)

![image](https://user-images.githubusercontent.com/37705250/39018177-7d4ab8ac-444f-11e8-8893-64ee53bbbd2b.png)

browser : Google Chrome Version 65.0.3325.181 (Official Build) (32-bit)

**Comment by Zecx** [comment]
mungkin karena browser beta ??

![image](https://user-images.githubusercontent.com/37705250/39018517-69d48644-4450-11e8-96ee-dbcb36dc5bc1.png)

**Comment by gvoze32** [comment]
Memang banyak bug di Firefox ini, tapi di saya bisa dibuka dengan baik.

**Comment by shirojishi** [comment]
sudah terselesaikan , masalahnya ternyata pada http , mintanya https 
thank you
