### ISSUE TITLE
[BUG] Unblock Non-ID & 64 bit

### ISSUE THREAD

**Issue by TrixPone** [gvoze32/unblockhostid#153]
Fitur Unblock-Non ID nya bug di 64 bit ?

![bug1](https://user-images.githubusercontent.com/35420947/39063510-e51ba780-44fd-11e8-87c9-05e9460fb140.png)
![bug2](https://user-images.githubusercontent.com/35420947/39063523-eb996f5c-44fd-11e8-9867-e58b41229d24.png)

Log error nya
[error.txt](https://github.com/gvoze32/unblockhostid/files/1932915/error.txt)

**Comment by gvoze32** [comment]
Setelah saya cek, benar, ada kesalahan tulis pada codingnya. Akan saya fix di update selanjutnya.

**Comment by gvoze32** [comment]
Fixed, silahkan update
