### ISSUE TITLE
[REQ] Hongfire.com and other site

### ISSUE THREAD

**Issue by Colokan** [gvoze32/unblockhostid#154]
Hello can you Unblock Hongfire.com and site other site on this list : 

hongfire.com
youporn.com
pornhub.com
hentai.ms
jjgirls.com
youjizz.com
e-hentai.org
imagefap.com
pandamovies.com
gosexpod.com
ixxx.cm
slutload.com
fuq.com
gamesofdesire.com
luscious.net
ice-porn.com
4tube.com
g6hentai.com
tubestack.com
hentaikey.com
hentai-foundry.com
subdesu-h.net
hentaistream.com
hentaischool.com
anime-sharing.com
gyutto.com

thank you very much :) 
you have done a good work so far (y)

**Comment by gvoze32** [comment]
**Tolong request yang belum ada di list**

_Data received:
ice-porn.com to below_
