### ISSUE TITLE
[REQ] https://fontawesome.com dan https://use.fontawesome.com

### ISSUE THREAD

**Issue by Ramacraft123** [gvoze32/unblockhostid#162]
Add dong situs ini
```
https://fontawesome.com
https://use.fontawesome.com
```
Ga bisa akses di telkom, IP address not found terus.
pls add mau nambah web font ke website.

**Comment by gvoze32** [comment]
Saya pake telkom lancar aja

**Comment by Ramacraft123** [comment]
Saya ga bisa
![Ga bisa gan](https://vgy.me/wj14BK.png)
