### ISSUE TITLE
[BUG] reddit.com (android application)

### ISSUE THREAD

**Issue by uciha753** [gvoze32/unblockhostid#164]
ga bisa akses reddit dari aplikasi android, tapi kalau via browser bisa, berlaku buat aplikasi lain juga seperti pornhub for android, dsb. apa memang trik ini hanya berpengaruh ke browser saja?

**Comment by gvoze32** [comment]
Seharusnya bisa, tapi gatau juga, mungkin sistemnya beda sama yang di PC.
