### ISSUE TITLE
[BUG] Netflix.com

### ISSUE THREAD

**Issue by aditos** [gvoze32/unblockhostid#184]
gw kok masih ga bs akses netflix ya? untuk site2 lain ud lancar. cuma netflix aja yg masi ke direct ke mercusuar.

mac user btw.

thanks!

**Comment by staclarapa** [comment]
nambahin ini, kalo gue bisa akses sih cuma lemot bgt. loading cover film di homenya aja lama bgt :(
 windows 10 + indihome

**Comment by aditos** [comment]
vpn gw ga bs - zenmate, at least Buat streaming. Kalo browsing bisa. yg bisa pake vpn apa ya?

**Comment by staclarapa** [comment]
@gvoze32 oalah gitu ya mas, ini saya nemu di http://unblocksites.co/en/2/unblock/netflix.com/ kalo dia nambahin hostnya gak cuma netflix.com doang tp ada beberapa cabangnya

2.19.60.89    assets.nflxext.com
104.123.109.22    ir.netflix.com
23.62.128.67    fast.com
52.85.219.129    media.netflix.com
34.213.151.116    www.netflix.com
34.211.85.116    help.netflix.com
52.41.100.236    jobs.netflix.com
128.30.52.100    www.w3.org
2.19.60.89    codex.nflxext.com
52.48.206.76    netflix.com

saya udh coba sih add yg diatas ke hosts tapi tetep sama aja sih. Barangkali clue bisa membantu nemuin fixnya

**Comment by gvoze32** [comment]
Yang diblock cuma Netflix.com, lainnya nggak, jadi ya masih belum bisa/gatau cara fixnya. Kecuali nemu ip khusus untuk region Indonesia.
