### ISSUE TITLE
[REQ] rarbgaccess.org

### ISSUE THREAD

**Issue by senpai28** [gvoze32/unblockhostid#187]

**Comment by gvoze32** [comment]
Why not using rarbg.to instead of that?

**Comment by ssvs09** [comment]
nambahin boleh gak? rarbg.to memang bisa diakses, tapi waktu menu halaman lain (http://rarbg.to/torrents.php, http://rarbg.to/chart.php, dll) munculnya internet positif. nah, ketika klik halaman lain itu, rarbgnya berubah jadi rarbgaccess.org

**Comment by gvoze32** [comment]
Checked today and it's yeah, will be added in the next update.

**Comment by senpai28** [comment]
Ok thx :)
