### ISSUE TITLE
[BUG] Danbooru and out.reddit isn't working

### ISSUE THREAD

**Issue by naufaldori** [gvoze32/unblockhostid#189]
danbooru.donmai.us

out.reddit.com whenever reddit directs to other site

**Comment by TrixPone** [comment]
also, since the Reddit redesign

The old interface now uses old.reddit.com

**Comment by naufaldori** [comment]
hmm my address is still on reddit.com despite the unchanging classic theme, but so does my youtube so maybe it's just my browser cookies

**Comment by gvoze32** [comment]
Checked today and no problem found. Please give more specific reason.

**Comment by naufaldori** [comment]
Sorry for late reply, here's the screenshot

![screenshot 38](https://user-images.githubusercontent.com/39834377/41100972-f2724c7c-6a8c-11e8-80e7-220fed873fa0.png)

**Comment by gvoze32** [comment]
Advanced - Proceed/Add Exception
