### ISSUE TITLE
[BUG] - reddit.com

### ISSUE THREAD

**Issue by cyberjunkey** [gvoze32/unblockhostid#198]
Pada reddit.com bila melakukan kegiatan surfing biasa sangat normal dan bekerja dengan baik. Tapi ketika ingin membuka link yang ada pada reddit menuju out.reddit.com yang terjadi adalah your connection is not secure dan ketika di add exception, yang ada muncul message ini pada JSON:

"Message | "User: anonymous is not authorized to perform: es:ESHttpGet"

**Comment by gvoze32** [comment]
Ip update received: 52.5.206.7
