### ISSUE TITLE
[BUG] netflix.com

### ISSUE THREAD

**Issue by rexcounty** [gvoze32/unblockhostid#199]
Setelah install unblockhost, buka reddit lancar, netflix juga lancar. Tapi saat masuk playback movie, muncul tulisan:

Whoops, something when wrong....

Internet Connection Problem
An Internet or home network connection problem is preventing playback. Please check your Internet connection and try again.

If the problem persists, please visit the Netflix Help Center.

Saya memakai ISP Indihome, BTW

**Comment by staclarapa** [comment]
akses kecepatan netflix dilimit sama indihome jadi mesti pake goodbye DPI jg

**Comment by rexcounty** [comment]
sayangnya saya pakai macOS dan goodbye dpi ga bisa di macOS :(
