### ISSUE TITLE
[REQ] Google Safe Search

### ISSUE THREAD

**Issue by cedrickson** [gvoze32/unblockhostid#274]
google.com/preferences

ISP Indonesia terutama Telkom sekarang gunakan setting safesearch secara default biar gabisa search macem2 kayak konten yang kita suka, gabisa didisable karena setelah saya cari ada IP address tersendiri buat jadiin safesearch secara default. Ini hanya bisa di-bypass jika gunakan VPN.

**Comment by cedrickson** [comment]
IP address saya? Berhubung sering ganti saya gabisa kasih
Sementara untuk google sepertinya ini di tweak sama pemerintah
Saya sudah coba cari IP addressnya google.co.id/preferences dan mencoba
masukkan ke host tetap tidak bisa.
Tapi uniknya ketika saya pakai VPN, bisa saya turn off Safe Search
google-nya.

2018-08-06 7:22 GMT+07:00 Syafa Adena <notifications@github.com>:

**Comment by gvoze32** [comment]
Silahkan cek di fitur Additional

**Comment by gvoze32** [comment]
Maksudnya Options
