### ISSUE TITLE
[BUG] javlibrary.com

### ISSUE THREAD

**Issue by ernaswiss** [gvoze32/unblockhostid#280]
Ngedirect ke example.com / lari ke example.com
![fawfwafawd](https://user-images.githubusercontent.com/12867379/43732604-55f8d9f4-99dc-11e8-963f-f4080ef95063.png)

**Comment by robbato** [comment]
di gue masih blankpage

**Comment by Bagus23** [comment]
gw pake tel*om tanpa proxy masih bisa buka, coba lagi mungkin tadi error.

**Comment by robbato** [comment]
Si bagus23 hoax. Dari dulu javlib udah kena iplus. mana mungkin tanpa proxy bisa
tolong dibuka lagi di gue masih blankpage pakai internethomo

![firefox_2018-08-13_07-25-44](https://user-images.githubusercontent.com/10296285/44008136-2cc774e4-9eca-11e8-8854-79c1043936ef.png)
