### ISSUE TITLE
[REQ] another soap sites 2

### ISSUE THREAD

**Issue by Bagus23** [gvoze32/unblockhostid#282]
sudah dicek manual, hasilnya ipochan atau can’t be reached.

vixen.com
tushy.com
lubed.com
babes.com
sexart.com
ftvgirls.com
hustler.com
iknowthatgirl.com
realitykings.com and rk.com
pornpros.com and pornprosnetwork.com
naughtyamerica.com
videobox.com
gfrevenge.com
teamskeet.com
exxxtrasmall.com
czechav.com
julesjordan.com
dogfartnetwork.com
passion-hd.com
fakehub.com
twistys.com
newsensations.com
clubseventeen.com
legalporno.com
fuckingawesome.com
stasyq.com
wickedpictures.com
metart.com
adultdeepfakes.com
bangbrosnetwork.com
brazzersnetwork.com
Ideapocket.com
oppai-av.com
wanz-factory.com
av-e-body.com
asiansexdiary.com

maaf kalo kebanyakan, cuma bantu ngelengkapin aja hehe

**Comment by gvoze32** [comment]
What the heck mate, get a real life

**Comment by Bagus23** [comment]
dang, berarti permintaan saya ditolak wkkw

![alt text](https://pbs.twimg.com/media/BvqhB99IMAAFd8J?format=jpg&name=orig)

**Comment by gvoze32** [comment]
Seenggaknya bantu nambahin line di raw.txt lah

**Comment by Bagus23** [comment]
caranya gimana boy, kalo ngerti udah bantu commit dari dulu, goblok euy :(

**Comment by Bagus23** [comment]
sek tak belajar

https://github.com/endymuhardin/belajarGit/blob/master/cara-berkontribusi-opensources-github.md

**Comment by gvoze32** [comment]
Edit raw.txt-nya aja, tambahin web yang ente req, contoh atasnya, nanti ipnya tak cari sendiri.

Ex:
[VIXEN.COM]

[TUSHY.COM]

gitu aja nanti tak terusin

**Comment by Bagus23** [comment]
iya ini lagi dikerjain 
btw ini yang dipilih yang mana gan ?

![alt text](https://image.prntscr.com/image/83uxjRe4S5mV-qX5RjHn4A.png)

**Comment by gvoze32** [comment]
di project saya ini cuma ada 1 branch. jadi buat branch baru aja

**Comment by gvoze32** [comment]
Seep

**Comment by gvoze32** [comment]
Done, bakalan ada bug karena gak gw cek satu-satu karena banyak bgt bgst. Kalo ada bug open issue aja terus jelasin bugnya dimana, nanti saya update.
