### ISSUE TITLE
[REQ] Matikan google safesearch

### ISSUE THREAD

**Issue by Ramacraft123** [gvoze32/unblockhostid#289]
ada ketentuan baru dari telkom (mungkin isp lain juga) utk mengarahkan traffic dari google dan youtube ke dns mereka yang memaksa safesearch utk selalu on (supaya ga ada konten tiiit yang masuk ke hasil search).

mungkin bisa ditambahkan utk mengembalikan ke semula. tks

**Comment by Chocolalolz** [comment]
ganti homepage mu dengan "google.co.uk" tanpa tanda kutip. Semoga membantu

**Comment by naufaldori** [comment]
kalau saya .co.id nggak bisa, tapi pakai .com bisa off

**Comment by gvoze32** [comment]
Cek menu Options
