### ISSUE TITLE
[BUG] Rule34.xxx, E621.net 

### ISSUE THREAD

**Issue by okdad** [gvoze32/unblockhostid#293]
![image](https://user-images.githubusercontent.com/26517194/43998455-5f6c3722-9e20-11e8-8e92-e173ef05d9ac.png)
![image](https://user-images.githubusercontent.com/26517194/43998475-cf34b4ee-9e20-11e8-8f3c-e22b14236d4a.png)

kemungkinan masalah dengan img.rule34.xxx dan static1.e621.net karena saya coba tidak bisa dibuka

**Comment by Bagus23** [comment]
ya benar sekali, nanti saya update
