### ISSUE TITLE
[BUG] Javlibrary.com

### ISSUE THREAD

**Issue by robbato** [gvoze32/unblockhostid#295]
Javlib masih gak bisa masuk
![firefox_2018-08-13_07-25-44](https://user-images.githubusercontent.com/10296285/44008195-cb0447f4-9eca-11e8-863f-3f149bb5ba89.png)

**Comment by Bagus23** [comment]
coba tunggu agan syafa jelasin masalah ini, soalnya di gw daridulu masih ga ada masalah pake file hostnya.

![alt text](https://image.prntscr.com/image/cN6r5BL2Rg6Mn-PC3Cx8Yg.png)
