### ISSUE TITLE
[BUG] tumblr.com

### ISSUE THREAD

**Issue by ReaMusey** [gvoze32/unblockhostid#297]
Masuk ke dashboard masih bisa. Tapi masuk ke "sitename".tumblr.com masih diblock
contoh : http://blahberry-pancake.tumblr.com/
![screenshot_65](https://user-images.githubusercontent.com/42333331/44014212-c2a25518-9ef4-11e8-86f0-515da95e66e5.png)

**Comment by Bagus23** [comment]
66.6.33.31 tumblr.com www.tumblr.com

**Comment by gvoze32** [comment]
Memang kalau subdomain harus add line lagi. Nanti saya coba carikan list subdomain tumblr apa aja yang di blokir.

**Comment by gvoze32** [comment]
Sudah saya cek, sub tumblr banyak banget yang diblok, will not update this
