### ISSUE TITLE
[BUG] Turn Off Google SafeSearch

### ISSUE THREAD

**Issue by ernaswiss** [gvoze32/unblockhostid#298]
maksudnya gmna ya? safe search tetap aktif
![image](https://user-images.githubusercontent.com/12867379/44051857-3c52bd9c-9f65-11e8-958a-36826a8c50fd.png)

**Comment by gvoze32** [comment]
Kalau sudah klik Turn off SafeSearch nanti sudah bisa kita matikan secara manual.

**Comment by LastRoze** [comment]
Tetep ga bisa bro, bisa minta tolong kasih cara yang bener yang bagaimana ?

**Comment by gvoze32** [comment]
Coba cari sesuatu, terus di bagian settings klik Turn off SafeSearch
