### ISSUE TITLE
[BUG] https://www.nutaku.net/games/fap-ceo/play/

### ISSUE THREAD

**Issue by ernaswiss** [gvoze32/unblockhostid#305]
Game Barunya Nutaku, Gambar Tidak muncul Dan Tidak Bisa Di Mainkan.
![image](https://user-images.githubusercontent.com/12867379/44399415-b6b4f480-a571-11e8-9e66-78bb62033a85.png)

**Comment by gvoze32** [comment]
No login access, will not fix
