### ISSUE TITLE
[DEV] Need Some Help

### ISSUE THREAD

**Issue by gvoze32** [gvoze32/unblockhostid#310]
Dikarenakan saya saat ini sedang tidak menggunakan koneksi dari telkom, maka dari itu saya meminta tolong untuk mengecek yang ada di issues, website mana saja yang tidak dapat diakses. Nanti akan saya fix kan. Terima kasih.

cc: @Bagus23

**Comment by Bagus23** [comment]
oke siap mhanx.

**Comment by Bagus23** [comment]
beberapa sudah di perbaiki.

**Comment by gvoze32** [comment]
Woah, big thanks, saya cuma butuh buat cek diblokir apa nggk padahal, eh di fix sekalian wkwk

**Comment by CoronA99** [comment]
barusan nyoba pake wifi Telkom(indiehome), masih kena ipo. Coba pindah make hostpot hape (tri) malah bisa(ga ada ipo nya).

terus itu kalau pake aplikasi(unblockhostID.exe) kaya masih ga ke use pas make wifi indigo

**Comment by gvoze32** [comment]
@CoronA99 Coba flush dns dan restart pc
