### ISSUE TITLE
[BUG] Versi unblockhostid android(non root) tidak bisa download

### ISSUE THREAD

**Issue by CoronA99** [gvoze32/unblockhostid#313]
Pada penggunaan unblockhostid yang versi android non root(pakai apk VPN), pas browsingnya bisa. tapi kalo download pada site yang udh di unblocknya ga bisa. Btw, saya pake ISP : Tri.

**Comment by gvoze32** [comment]
Memang non root agak susah gan, saran saya coba pake Intra saja.
