### ISSUE TITLE
[BUG] Reddit 

### ISSUE THREAD

**Issue by Adhitore** [gvoze32/unblockhostid#316]
untuk reddit redesign gabisa negeload home, tapi kalo buka per subreddit bisa. Untuk reddit lama (old.reddit.com) atau belum beralih ke redesign gaada masalah buat home.

Yang dimobile juga gitu, buat Home gabisa ngeload sementara popular dan buka per subreddit bisa

**Comment by gvoze32** [comment]
Memang agak susah, kadang bisa kadang nggak, belum tahu masalahnya dimana, mungkin akan di fix pada v42 nanti.
