### ISSUE TITLE
[BUG] Tumblr.com hanya bisa melihat dashboard.

### ISSUE THREAD

**Issue by ssvs09** [gvoze32/unblockhostid#318]
akses ke tumblr.com untuk login & halaman dashboard (setelah berhasil login) muncul halaman & gambar. (preview [1](https://images2.imgbox.com/6c/3f/Z3s2rmXr_o.png) & [2](https://images2.imgbox.com/2a/97/xDwoi89k_o.png)) tapi kalau mau membuka ke profile tertentu, jadinya gak muncul. (preview [1](https://images2.imgbox.com/60/f2/Hj2hx2oT_o.png) & [2](https://images2.imgbox.com/ab/82/ULe0wnNj_o.png))

sekalian mau tanya. 
1. kbagi kenapa dihapus ya? apa karna sudah tidak diblock? pake indihome langsung internet positif. hehe.
1. yg turn off safe search google setelah di klik, rasanya masih tetep on di saya. (preview [1](https://images2.imgbox.com/5c/2c/UNdWQWvJ_o.png))

**Comment by gvoze32** [comment]
1. Kbagi akan resmi ditutup.
2. Turn of manual di Settings

Memang tumblr punya banyak sub, dan yang diblokir itu banyak sekali, jadi untuk melist satu-satu kami masih belum mampu untuk melakukannya

**Comment by ssvs09** [comment]
oh, baru tau kalo kbagi akan resmi ditutup. baiklah.

turn off manual di settings maksudnya di tombol Settings kan? gak ada perubahan kalo di saya.
