### ISSUE TITLE
Mohon izin untuk membuat module magisk

### ISSUE THREAD

**Issue by Muhajaya** [gvoze32/unblockhostid#319]
Saya sudah melihat pada halaman [ini ](https://github.com/gvoze32/unblockhostid/blob/master/INSTALL.md) tentang cara pemasangan pada Android, tapi untuk lebih mudah, saya ingin membuat nya sebagai module magisk.

Untuk itu saya meminta izin untuk membuatnya agar bisa lebih simple karena magisk module systemlessy
Terimakasih
[Unblockhostid.zip](https://github.com/gvoze32/unblockhostid/files/2342962/Unblockhostid.zip)

**Comment by gvoze32** [comment]
Saya belum mengerti penggunaan Magisk, tapi saya rasa sama saja ya seperti replace file pada umumnya, hanya saja sekali klik begitu?

**Comment by Adhitore** [comment]
nah ini nih. buatin mas muha wkwk, males pake vpn host

**Comment by Muhajaya** [comment]
Kalau magisk enaknya systemless, jadi untuk devices yg memiliki update OTA tidak perlu khawatir. Karena kalau di replace langsung, alhasil tidak bisa update langsung.
Karena kalau modul magisk, file tidak tereplace, tapi system akan membaca file host yg berada di dalam folder magisk seolah2 file tersebut berada di system.

**Comment by gvoze32** [comment]
Oh gitu, oke masih bingung buat updatenya, soalnya yang ngerti magisk gak banyak. Kalau setiap rilis pake update magisk keknya gk worth sama yang pakenya.

**Comment by Muhajaya** [comment]
Saya izin bikin pak :) minta izin buat download file hosts nya, lalu saya jadikan magisk module begitu maksud saya :D

**Comment by Muhajaya** [comment]
Kalau memang begitu, mungkin saya pakai untuk penggunaan pribadi saja ya

**Comment by gvoze32** [comment]
Oh, silahkan kalau begitu
