### ISSUE TITLE
[REQ] Unblock netflix di mac os

### ISSUE THREAD

**Issue by ibnuh** [gvoze32/unblockhostid#321]
Apakah ada aplikasi sejenis GoodbyeDPI untuk mac os?

**Comment by raytedjaja** [comment]
btw hosts yang netflix sama di nslookup beda yah

**Comment by ibnuh** [comment]
ga nemu goodbyeDPI buat macos, terpaksa nonton di vm, lancar jaya

![image](https://user-images.githubusercontent.com/18393879/45392130-289fcb80-b650-11e8-93a3-2b608ba7ca1c.png)

**Comment by alionar** [comment]
Kalo di macos, setelah tambahin semua IP domain netflix coba ganti DNS OS-nya pake Cloudflare sama Google dns. Saya sudah coba dan berhasil di indihome
