### ISSUE TITLE
[BUG] hanime.tv

### ISSUE THREAD

**Issue by thelazt16** [gvoze32/unblockhostid#322]
- Tidak bisa login
FIX = 104.27.240.171 tapi.hanime.tv

**Comment by thelazt16** [comment]
+ Slow load
FIX =
104.27.241.171 hanime.tv
104.27.240.171 www.hanime.tv uploads.hanime.tv ark.hanime.tv *ark.hanime.tv oberon.hanime.tv *oberon.hanime.tv m.hanime *.hanime.tv

**Comment by gvoze32** [comment]
Ok thanks, akan diperbarui di uptate berikutnya
