### ISSUE TITLE
[REQ] Google Safe Search

### ISSUE THREAD

**Issue by trusta77** [gvoze32/unblockhostid#333]
Beberapa bulan terakhir pencarian melalui google kalo ga pake vpn hasilnya bakalan kena safesearch (meskipun sudah dimatikan). 

Contoh hasil pencarian ranpa vpn:
![image](https://user-images.githubusercontent.com/40566453/45595796-3f8d4780-b9db-11e8-987e-f47dadc413cb.png)
Contoh Hasil pencarian menggunakan vpn: 
![image](https://user-images.githubusercontent.com/40566453/45595788-26849680-b9db-11e8-832d-6334b6a71ca3.png)

Kira-kira ada ga ya solusi untuk masalah yg satu ini?

**Comment by gvoze32** [comment]
Bukannya sudah ditambahkan fiturnya?

**Comment by trusta77** [comment]
Maaf sebelumnya ane miss pas baca changelog  nya. Tapi yang ini barusan udah pake versi 42 tapi hasilnya masih begitu.

**Comment by gvoze32** [comment]
Coba flush dns, restart pc

**Comment by trusta77** [comment]
Sudah dicoba tapi masih sama.

**Comment by gvoze32** [comment]
Cara mematikannya manual, di setting googlenya

**Comment by trusta77** [comment]
![ezgif-3-c97d0a278f](https://user-images.githubusercontent.com/40566453/45657753-d78f4c00-bb15-11e8-8a30-cec5f33b21b7.gif)

**Comment by py7hon** [comment]
Coba mas pakainya jangan .co.id coba pakai tld country lainnya
seperti [ini](https://www.google.co.jp/search?ei=a_yoW6S8BMzVvgSDk7DYCg&q=site%3Anekopoi.care&oq=site%3Anekopoi.care&gs_l=psy-ab.3...1435.10979.0.11157.27.23.2.0.0.0.353.2659.8j10j1j1.20.0....0...1c.1.64.psy-ab..6.6.806...0j0i10k1j0i67k1j0i131k1j0i10i3k1.0.ASWUtoMplPs)

**Comment by trusta77** [comment]
> Coba mas pakainya jangan .co.id coba pakai tld country lainnya
> seperti [ini](https://www.google.co.jp/search?ei=a_yoW6S8BMzVvgSDk7DYCg&q=site%3Anekopoi.care&oq=site%3Anekopoi.care&gs_l=psy-ab.3...1435.10979.0.11157.27.23.2.0.0.0.353.2659.8j10j1j1.20.0....0...1c.1.64.psy-ab..6.6.806...0j0i10k1j0i67k1j0i131k1j0i10i3k1.0.ASWUtoMplPs)

Nah ini, bisa gan, makasih banyak, ga kepikiran ane kalo domainnya ngaruh.
