### ISSUE TITLE
SORRY

### ISSUE THREAD

**Issue by gvoze32** [gvoze32/unblockhostid#368]
Maaf belum bisa update untuk beberapa hari ke depan, soalnya banyak tugas kuliah dan sekarang sedang mengerjakan program baru untuk projek ini agar lebih simpel dan responsif, mungkin akan saya convert ke bahasa yang lebih modern yaitu C# (sekarang menggunakan VB), dan itupun akan cukup menyita waktu, jadi ya... stay tune!

**Comment by gvoze32** [comment]
Updated the first for the app https://github.com/gvoze32/unblockhostid/commit/d64421c6786f505ae4d0c6603e85e683b767abb3

**Comment by perkasajob** [comment]
No Sorry, Thank You So Much !!!!!, Arigatou, don't feel to thank you enough, THANK YOU
