### ISSUE TITLE
[BUG] Netflix.com Lambat

### ISSUE THREAD

**Issue by ldiadam** [gvoze32/unblockhostid#389]
Akses Netflix.com Lambat,
Tetapi dicoba speedtest di Fast.com (Speedtest Netflix) koneksi dari PC saya ke Server Netflix Full Speed.

**Comment by gvoze32** [comment]
Sebenarnya tidak ada kaitannya dengan speedtest netflix, kami juga masih cari tau dimananya, tapi yang pasti itu throttling speed oleh indihome.
