### ISSUE TITLE
[BUG] hitomi.la

### ISSUE THREAD

**Issue by ieatmangga** [gvoze32/unblockhostid#395]
halaman terbuka, thumbnail muncul, tapi pas gambar dibuka, hasilnya blank,  download pun tidak bisa. delete lines hitomi la di host file + vpn bisa baru bisa dibuka

**Comment by gvoze32** [comment]
Sudah di fix kemarin, coba update ke versi terbaru

**Comment by ieatmangga** [comment]
sebelum post, sudah saya update kok.

**Comment by gvoze32** [comment]
Coba clear dns, dan restart komputer, soalnya di saya sudah work normal

**Comment by ieatmangga** [comment]
update: habis clear dns seperti yg diinstruksikan, sekarang udah bisa.tapi setelah saya saya cek ada beberapa situs yg gak kebuka; pertanyaannya, bisa tanya disini atau buat thread baru? sama sekedar info, saya gak bisa baca online di fakku, tapi setelah saya tambah ip didapet dari search, sekarang bisa dibuka.
 ipnya : 104.20.208.29	books.fakku.net
104.20.209.29   books.fakku.net
