### ISSUE TITLE
[BUG] Netflix.com not working on Mac.

### ISSUE THREAD

**Issue by moecantplay** [gvoze32/unblockhostid#397]
Running on MacBook Pro (2017) 13" Non-Touchbar, with MacOS Mojave (Version 10.14.1)

Netflix.com wasn't able to play any videos.
![image](https://user-images.githubusercontent.com/28852435/49061412-44744000-f243-11e8-995d-7da3526de45d.png)

I tried copy pasting
`curl -sfLS https://raw.githubusercontent.com/gvoze32/unblockhostid/master/hosts >> /etc/hosts`

but it said access denied. So I am still using the old method which is copy pasting the IP Addresses of Netflix to _/etc/hosts_ through `sudo nano /etc/hosts`

**Comment by adadion** [comment]
> I tried copy pasting
curl -sfLS https://raw.githubusercontent.com/gvoze32/unblockhostid/master/hosts >> /etc/hosts

> but it said access denied. 

'etc' folder are system protected folder, therefore you need to login as superuser first using 'su' command. But you're made it with the old method.

My suggestion at this moment, just remove or comment out (put '#' just at the beginning of) any netflix ip in those hosts file.
