### ISSUE TITLE
[BUG] 4chan Masih terblokir

### ISSUE THREAD

**Issue by andretkj1** [gvoze32/unblockhostid#411]
4chanku masih terblokir 
https://imgur.com/KxF2hen

**Comment by gvoze32** [comment]
Coba flush dns di options, terus restart pc, kalo masih tetep nanti saya cek

**Comment by andretkj1** [comment]
Ok nanti saya coba Kali udah dirumah

**Comment by andretkj1** [comment]
Masih tidak bisa saya sudah coba flushns beberapa kali + restart

Pada tanggal Sen, 17 Des 2018 pukul 09.31 Andre Citro <andrejjiiee@gmail.com>
menulis:
