### ISSUE TITLE
[REQ] Apakah ada versi macOS?

### ISSUE THREAD

**Issue by krisnaw** [gvoze32/unblockhostid#413]

**Comment by samdgea** [comment]
I agree, please working for macOS user.

**Comment by krisnaw** [comment]
FYI:
- For the host, you can add easily using terminal.
But Goodbye DPI isn't available for macOS.

**Comment by samdgea** [comment]
I did add netflix IPs to host but still not working, any ideas ?

**Comment by samdgea** [comment]
I did add IPs to host manually using terminal, and its working. thanks

**Comment by gvoze32** [comment]
Here's the manual:
https://github.com/gvoze32/unblockhostid/blob/master/INSTALL.md#linux--bsd--macos

**Comment by Monastere** [comment]
doesnt work @gvoze32
