### ISSUE TITLE
[REQ] Goodbye DPI untuk android

### ISSUE THREAD

**Issue by winsenwonady** [gvoze32/unblockhostid#414]
k ada nggak Goodbye DPI untuk android biar kecepatan tidak diblokir dengan provider?

**Comment by krisnaw** [comment]
Kalau pakai Android Pie, bisa coba pakai DNS Cloudflare

https://blog.cloudflare.com/enable-private-dns-with-1-1-1-1-on-android-9-pie/

**Comment by krisnaw** [comment]
@winsenwonady coba saja cari cara mengganti DNS di Android, lalu masukan DNS dari cloduflare

**Comment by gvoze32** [comment]
Apakah dengan DNS tersebut Netflix bisa tembus? @krisnaw

**Comment by winsenwonady** [comment]
Tidak bisa jaringan masih lambat
