### ISSUE TITLE
[REQ] Installation For Non Rooted Android Device

### ISSUE THREAD

**Issue by tonilicious** [gvoze32/unblockhostid#422]
Halo, saya sudah mencoba mengikuti cara instalasi untuk non-rooted device seperti yang dijelaskan, tetapi aplikasi tidak bekerja seperti seharusnya.
Berikut lampirannya :
1. (Tampilan utama app)
https://www.photobox.co.uk/my/photo/full?photo_id=501533142584
2. (Host editor)
https://www.photobox.co.uk/my/photo/full?photo_id=501533143411
3. (Import host)
https://www.photobox.co.uk/my/photo/full?photo_id=501533142879
4. (Select unblockid.exe)
https://www.photobox.co.uk/my/photo/full?photo_id=501533142788
5. (.....)
https://www.photobox.co.uk/my/photo/full?photo_id=501533143608

**Comment by tonilicious** [comment]
For opening the images attached: 
Hold the link > open incognito

**Comment by tonilicious** [comment]
Apabila ada masalah dalam membuka file lampiran, biar saya jelaskan disini:
Import host untuk file exe tersebut tidak mengubah apapun dalam aplikasi, (tidak ada domain keluar)

**Comment by gvoze32** [comment]
Bukan .exe yang diimport, tapi "hosts"
