### ISSUE TITLE
[BUG] TIdak bisa browsing 

### ISSUE THREAD

**Issue by noxx77** [gvoze32/unblockhostid#430]
[BUG]  Gatau kenapa saya jd tidak bisa browsing. Selalu keluar perintah untuk memasukan capthca, tapi masalahnya captcha nya tidak bisa disolve. Dibawah saya lampirkan screencap

https://imgur.com/a7vUgZY

**Comment by gvoze32** [comment]
Ini kenapa? Kami tidak pernah memasukkan google di list hosts kecuali di fitur "Turn off Safesearch"
