### ISSUE TITLE
[BUG] tidak bisa menginstall unblockhostid

### ISSUE THREAD

**Issue by fadhluu** [gvoze32/unblockhostid#431]
![screenshot 1](https://user-images.githubusercontent.com/38921923/50877605-29314e80-1405-11e9-9bb1-f1fd4f0609f8.png)

tidak bisa menginstall unblockhostid

**Comment by Nosoba** [comment]
udah as admin ga?

tapi lebih mudah manual sih.. tinggal copy hosts taruh di system32/drivers/etc/ disini.. tinggal replace aja :)

**Comment by fortoszone** [comment]
iya nih akses the file hosts nya denied mulu

**Comment by fortoszone** [comment]
Udah bisa deh. Harus pause dulu antivirusnya walaupun .exe nya ngga kedetek

**Comment by gvoze32** [comment]
Udah fix?

**Comment by fadhluu** [comment]
udah fix bray, makasih sarannya semua.
