### ISSUE TITLE
[ASK] Cara hapusnya gimana?

### ISSUE THREAD

**Issue by noxx77** [gvoze32/unblockhostid#432]
seperti judul. Ini cara hapusnya gimana yak

**Comment by gvoze32** [comment]
Hapus apa?

**Comment by Nosoba** [comment]
lain kali di backup dulu makanya hosts defaultnya wkkw

**Comment by gvoze32** [comment]
Kalo maksudnya kembalikan seperti semula, bisa pakai fitur "Rollback" di Settings
