### ISSUE TITLE
[BUG] dmm.co.jp

### ISSUE THREAD

**Issue by 0xh3LL0** [gvoze32/unblockhostid#436]
sample9.dmm.co.jp

buat download game trial

**Comment by vnlovers** [comment]
Wah, orang indo ternyata

**Comment by 0xh3LL0** [comment]
masih kena internet positif

http://sample9.dmm.co.jp/digital/pcgame/digination_0001/digination_0001t.zip

**Comment by gvoze32** [comment]
Are you using linux? Sorry, i forgot to commit the hosts file. Please try again.

**Comment by 0xh3LL0** [comment]
skrg udah bs...
