### ISSUE TITLE
[ASK] How to install on mac?

### ISSUE THREAD

**Issue by Monastere** [gvoze32/unblockhostid#437]
hey i'm just a mere normies wanting to watch netflix on my mac, too bad tel-son-of-a-fucking-bitch-kom decided to block it. 

I've read the installation guide, it includes one for linux and mac. i tried copy pasted the thing to my terminal but "command not found".

help?

**Comment by gvoze32** [comment]
Try this

sudo curl -sfLS https://raw.githubusercontent.com/gvoze32/unblockhostid/master/hosts >> /etc/hosts

Please reply this comment if it's work

**Comment by tmothi** [comment]
> sudo curl -sfLS https://raw.githubusercontent.com/gvoze32/unblockhostid/master/hosts >> /etc/hosts

The above works for me on a Mac, thanks a lot! However, when I access netflix.com (in Indonesia), it's very slow. Do I need to do anything else? Kindly advise. I'm a total beginner on this. thank you!

**Comment by tmothi** [comment]
Second doesn't work. Mac terminal doesn't recognize "wget".

**Comment by gvoze32** [comment]
Okay thanks

**Comment by Monastere** [comment]
thanks man, it definitely works! i had to learn quite a bit about xcode, hb, etc tho. thanks!
