### ISSUE TITLE
[PROJECT] GoodbyeDPI for Linux

### ISSUE THREAD

**Issue by gvoze32** [gvoze32/unblockhostid#445]
Learn [zapret](https://github.com/bol-van/zapret)

Coming soon...
[NETFLIX.md](https://github.com/gvoze32/unblockhostid/blob/master/NETFLIX.md#linux)

**Comment by data4pass** [comment]
[zapret_readme_deepl.txt](https://github.com/gvoze32/unblockhostid/files/2795165/zapret_readme_deepl.txt)

If by any chance you need it, here's zapret's readme translated via https://deepl.com/, which I think has a better translation quality compared to Google Translate.

**Comment by gvoze32** [comment]
Woah, thanks, really helps

**Comment by gvoze32** [comment]
> _**Translate to Indonesian**_

**Comment by izzuddinsyamil** [comment]
ada langkah - langkah yg lebih enak ga bang buat ubuntu 18.04? saya sudo apt-get install linux-image-3.16 kok Unable to locate package ya?

**Comment by gvoze32** [comment]
@izzuddinsyamil 
Belum bisa buat langkahnya, belum bisa nyoba soalnya

**Comment by teddymartadinata** [comment]
is there any goodbyedpi / zapret for macos based? thanks

**Comment by FarrelF** [comment]
@teddymartadinata: You can using [Green Tunnel](https://github.com/SadeghHayeri/GreenTunnel) instead zapret, which supports Windows, GNU/Linux (Or, Debian GNU/Linux and it's derrivatives), and macOS.

Not only that, the application has a simple GUI that makes easiest to use.

**Comment by gvoze32** [comment]
> 
> 
> @teddymartadinata: You can using [Green Tunnel](https://github.com/SadeghHayeri/GreenTunnel) instead zapret, which supports Windows, GNU/Linux (Or, Debian GNU/Linux and it's derivatives), and macOS.
> 
> Not only that, the application has a simple GUI that makes easiest to use.

I'll take a look
