### ISSUE TITLE
[ASK] How to turn it off?

### ISSUE THREAD

**Issue by Monastere** [gvoze32/unblockhostid#448]
suddenly the video wont load at all, even in another network that doesnt ban netflix. whats wrong? i was wondering if i should turn it off. im using mac

**Comment by gvoze32** [comment]
I'm not sure the problem is caused by this app. But try this, just copy and replace the code.
http://osxdaily.com/2014/04/12/restore-original-hosts-file-mac/

Let me know if the problem is fixed or not.
