### ISSUE TITLE
[REQ] rapidvideo.com

### ISSUE THREAD

**Issue by adhitrm** [gvoze32/unblockhostid#459]
Untuk beberapa user Indihome, rapidvideo diblokir dengan error ERR_NAME_NOT_RESOLVED

**Comment by gvoze32** [comment]
Bisa di saya, bisa sertakan ss?

**Comment by adhitrm** [comment]
Maaf, ternyata di file hosts saya rapidvideo nya diset ke 0.0.0.0.
