### ISSUE TITLE
request

### ISSUE THREAD

**Issue by abiyosohar** [gvoze32/unblockhostid#46]
therockcocks.com
website bagus authornya gambar komik gitu
makasih berat :)

**Comment by gvoze32** [comment]
Saya sudah coba akses bisa kok, langsung redirect ke rockcocks.slipshine.net. Coba anda cek lagi.

**Comment by gvoze32** [comment]
![image](https://user-images.githubusercontent.com/28755051/33801804-5bb19ebc-dd99-11e7-8a97-5cd51c02c430.png)

**Comment by abiyosohar** [comment]
![screenshot_2](https://user-images.githubusercontent.com/30460411/33807003-ea25521a-de02-11e7-81dd-3ef2e2147683.jpg)

maaf gan di tempat saya begini tampilannya
backbone isp (starnet) yang saya pakai indosat jadi mungkin agak beda sama internet positif si indihome

**Comment by gvoze32** [comment]
Oh, beda ISP, ok ditunggu ya...

**Comment by Kutukertas** [comment]
Gan official app nya reddit di android gk bsa ya?

**Comment by gvoze32** [comment]
@Kutukertas 
Tolong buka issue baru, tapi memang benar saya lihat memang tidak bisa, nanti saya update ipnya lagi. Tapi tolong sebelumnya buka issue baru ya

**Comment by gvoze32** [comment]
@Kutukertas Fixed, coba sebelum install, hapus dulu hosts yang ada, baru kemudian copy yang baru.

**Comment by gvoze32** [comment]
Done, silahkan update

**Comment by gvoze32** [comment]
Pake yang Experimental ya
