### ISSUE TITLE
[SELL] Akun Netflix dan Spotify

### ISSUE THREAD

**Issue by gvoze32** [gvoze32/unblockhostid#464]
# Akun Spotify Premium

Kenapa Premium?
- Tidak ada iklan
- Bisa ganti musik sesuka kita
- Download musik dan putar tanpa internet
- Mainkan lagu apa saja
- Musik lebih jernih
- Tampilan beda dari akun gratis

Garansi 2 Minggu (Random Expired+Auto Renew)
- Masa aktif selamanya asal password tidak diganti sama yang punya
- Akun akan diganti jika gagal login

Harga: 10k via OVO & Tsel

*Akun yang kami berikan tidak selalu berasal dari negara Indonesia

# Akun Netflix Premium UltraHD 

Kenapa Premium?
- Kualitas UHD
- Tonton film HD di laptop, tab, hp, smart tv, apple tv, xbox, playstation
- Film dan serial tv tidak terbatas
- Legal

Harga: 20k & 160k via OVO only

Durasi 1 Bulan & Lifetime
- Garansi full untuk 1 bulan, khusus lifetime garansi 1 tahun
- Akun akan diganti jika gagal login

**Comment by falbjm** [comment]
mantap gan...

**Comment by gvoze32** [comment]
@abdurqodir1999 
Sure, just email me at gvoze32@gmail.com

**Comment by abdurqodir1999** [comment]
jd reseller gimana bang

**Comment by gvoze32** [comment]
Reseller akun apa?

**Comment by abdurqodir1999** [comment]
spotify premium

**Comment by gvoze32** [comment]
Untuk reseller aku kasih harga khusus, 5k aja, kamu bisa jual dengan harga
10k. Mekanismenya, kalau kamu udah ada pembeli. Kamu trf ke aku, nanti aku
kasih akunnya. Soal garansi kalau semisal akun mati bisa minta lagi ke aku.

**Comment by abdurqodir1999** [comment]
saya ke situ, bayar transfer/ pulsa

pulsa aje deh min wkwk 😂

**Comment by gvoze32** [comment]
Ovo nggak ada?

**Comment by abdurqodir1999** [comment]
gojek ada, ovo blom bikin sih
gmn?

**Comment by gvoze32** [comment]
Coba bikin dulu om 😂, sementara gopay dulu gapapa sih

**Comment by abdurqodir1999** [comment]
ni baru instal ovo

**Comment by gvoze32** [comment]
Woke

**Comment by abdurqodir1999** [comment]
terus???
misal ada orang beli nih...
gmn

**Comment by gvoze32** [comment]
Kontak saya aja, WA aja deh biar lebih gampang +1 (202) 858-5180

**Comment by YogaSakti** [comment]
laporin bug di github issue ❎❎❎
ngiklan di github issue ✅✅✅

**Comment by erdinhrmwn** [comment]
mantap bang

**Comment by RKPW** [comment]
Jejak dulu ya

**Comment by damzaky** [comment]
marketing 101

**Comment by AnomSanjaya** [comment]
Asw S4 Marketing wkkwwkkw

**Comment by YusufArifin** [comment]
interested

**Comment by vexxe** [comment]
I'm interested. But the question is, is the Spotify a phised account from someone else? I heard it on Reddit.

**Comment by gvoze32** [comment]
@YusufArifin email me
@vexxe kind of that

**Comment by gvoze32** [comment]
Now i'm selling lifetime too

**Comment by vexxe** [comment]
How much for the lifetime account?

**Comment by gvoze32** [comment]
Rp. 160.000 with 1 year guarantee

**Comment by vexxe** [comment]
That's a nice price right there. I might consider to buy it because Spotify
gonna change its ToS for people who use adblockers and cracked apps to
bypass their ads.

I'll get in touch later when I made up my mind. Thanks.

Pada Senin, 11 Februari 2019, Syafa Adena <notifications@github.com>
menulis:

> Rp. 160.000 with 1 year guarantee
>

**Comment by trusta77** [comment]
Check email dong gan.
