### ISSUE TITLE
[BUG] https://sukebei.nyaa.si/

### ISSUE THREAD

**Issue by TakadaWang** [gvoze32/unblockhostid#465]
Keblok Sucuri Firewall di saya. Ada apa ya?

Pakai isp lain (data telkomsel) kebuka. 

https://i.imgur.com/SGfzSoi.png

**Comment by py7hon** [comment]
> Keblok Sucuri Firewall di saya. Ada apa ya?
> 
> Pakai isp lain (data telkomsel) kebuka.
> 
> https://i.imgur.com/SGfzSoi.png

coba di flush dns/clear cookie/ dari chrome bisa ke `chrome://net-internals/#dns` untuk clear hosts cache atau bisa ke `chrome://net-internals/#proxy` dan klik `clear bad proxies`

**Comment by AgusHerculeng** [comment]
Sama gan ane jg keblok. Clear hosts cache pakek `chrome://net-internals/#dns` nggak ngefek. Di `chrome://net-internals/#proxy` nggak ada pilihan clear bad proxies jg

**Comment by gvoze32** [comment]
Ini kasusnya kek javlib, ntar ane fix

**Comment by py7hon** [comment]
> Ini kasusnya kek javlib, ntar ane fix

Saran sih mending buat pac server aja gan

**Comment by gvoze32** [comment]
Itu gmn?

**Comment by gvoze32** [comment]
Malah ribet sih, masih mending pake DoH

**Comment by py7hon** [comment]
> Malah ribet sih, masih mending pake DoH

kalau untuk DoH memang tetapi kalau pac itu kan dia sudah auto 
lebih lengkapnya http://findproxyforurl.com/

**Comment by gvoze32** [comment]
Kalo proxy biasanya ngaruh ke speed
