### ISSUE TITLE
[BUG] manhwahentai.com

### ISSUE THREAD

**Issue by nishimiyachan** [gvoze32/unblockhostid#467]
Can't be accessed
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by gvoze32** [comment]
more specific please

**Comment by gvoze32** [comment]
mine is normal

**Comment by nishimiyachan** [comment]
Wait... I'm going to update the host then I'll tell you

**Comment by nishimiyachan** [comment]
it said  NET::ERR_CERT_COMMON_NAME_INVALID
I think this because my provider which is XL 
Mau dibuka di hp atau di PC sama aja GK bisa, tapi kalo paket VPN lancar jaya

**Comment by nishimiyachan** [comment]
It's weird now it's working again lol
BTW thanks
