### ISSUE TITLE
[BUG] xvideos.com

### ISSUE THREAD

**Issue by vantovelhiruzen** [gvoze32/unblockhostid#469]
Untuk ketentuan request, silahkan sertakan kode untuk issue yang dibahas dengan:

[REQ] - Untuk yang mau merekomendasikan situs baru untuk di unblock.

[BUG] - Untuk yang mau melaporkan adanya bug di salah satu situs. Wajib melampirkan detail tentang bug tersebut di deskripsi.

Contoh request untuk situs baru: [REQ] example.com

Contoh request untuk bug: [BUG] example.com

Sertakan juga di bagian apa bugnya, misal masih terblokir, gambar tidak muncul, dsb. 

Pastikan website yang akan direquest belum tersedia di list SITES.md:
https://github.com/gvoze32/unblockhostid/blob/master/SITES.md (Gunakan CTRL+F untuk mencari)

Bagi yang request tidak sesuai ketentuan, tidak akan saya kerjakan, terima kasih.

**Comment by gvoze32** [comment]
More specific pls

**Comment by vantovelhiruzen** [comment]
![image](https://user-images.githubusercontent.com/41057289/52485637-e9b87680-2beb-11e9-89b6-0ccb1f65bcd3.png)

**Comment by gvoze32** [comment]
Di saya kok normal ya, yang lain ada yang mengalami juga? Coba buka ini apakah diredirect ke internet positif atau muncul tulisan error http://xvideos-cdn.com/

**Comment by vantovelhiruzen** [comment]
![image](https://user-images.githubusercontent.com/41057289/52533653-7f2d4500-2d69-11e9-871b-75e6094c587e.png)
Error sih ini kayaknya , internet lancar kok ke website lain bisa.

**Comment by vantovelhiruzen** [comment]
Tolong di close postnnya , sudah bisa dibuka seperti semula -/\-
