### ISSUE TITLE
[BUG] JAVFOR.ME - Masih Terblokir

### ISSUE THREAD

**Issue by 71SOO** [gvoze32/unblockhostid#477]
[BUG] JAVFOR.ME

Situs Javfor.me Masih Terblokir Oleh Internet Positif

**Comment by ssvs09** [comment]
nimbrung nih, udah pake yang terbaru kah? di aku bisa kok.
![image](https://user-images.githubusercontent.com/38489705/52585899-a3238000-2e68-11e9-8cf7-1fdee902e0ef.png)
