### ISSUE TITLE
[BUG] yourporn.sexy (Video won't play)

### ISSUE THREAD

**Issue by trusta77** [gvoze32/unblockhostid#483]
Can't play video.

**Comment by gvoze32** [comment]
Here's the sample, still don't know which one the hosts server is.

> data-vnfo='{"5c72970b5228a":"\/cdn\/c10\/w2a0j2nzi6f77zm441pzu2050\/HFjCXn-gnc3XXZWpyJwegw\/t1551116149\/u51by6o8dak7nah3act3oda975c\/852ck7c239j760bbx5p2s238vaj.mp4"}'>

**Comment by trusta77** [comment]
is it trafficdeposit.com? like this one?

![image](https://user-images.githubusercontent.com/40566453/54165803-d91e4900-4494-11e9-8870-6e719f0c00c5.png)

idk, how do you usually find it out?

**Comment by gvoze32** [comment]
Maybe

**Comment by gvoze32** [comment]
Can vpn play video on that website?

**Comment by trusta77** [comment]
yep, totally. no problem with vpn.

**Comment by trusta77** [comment]
Wait, barusan pindah alamat dia ke sxyprn.com. Udah bisa di play.
