### ISSUE TITLE
[BUG] netflix.com on indihome

### ISSUE THREAD

**Issue by anakanjing** [gvoze32/unblockhostid#485]
on indihome network connection, successfully login and browse the movies, but after clicked play button... the screen goes black for longtime.. and got some error message (some network connection issues) 

pls help

**Comment by gvoze32** [comment]
Read the [NETFLIX.md](https://github.com/gvoze32/unblockhostid/blob/master/NETFLIX.md)

**Comment by teddymartadinata** [comment]
Do you have any guidance re GoodbyeDPI/something similiar for macOS? I haven't found any on the md files

**Comment by gvoze32** [comment]
Currently no

**Comment by teddymartadinata** [comment]
Thanks
