### ISSUE TITLE
bug chan.sankakucomplex.com

### ISSUE THREAD

**Issue by lwiwensky1** [gvoze32/unblockhostid#49]
when i open it, its only showing me this
![image](https://user-images.githubusercontent.com/29788699/34030370-2dc2e420-e19f-11e7-8ea7-7f49dc5cecd4.png)

**Comment by gvoze32** [comment]
Okay please wait, i found another ip on that website

**Comment by gvoze32** [comment]
Okay please wait, i found another ip for that website

**Comment by gvoze32** [comment]
Done, please update
