### ISSUE TITLE
[BUG] Netflix.com

### ISSUE THREAD

**Issue by chiprockets** [gvoze32/unblockhostid#490]
Tadi siang nyoba buka Netflix via Firefox dan app yang ada di Microsoft Store bisa, tapi malam ini kalo login di app selalu balik ke laman login, dan ngebuka situs di Firefox servernya not responding

**Comment by wildrmdn88** [comment]
me 2 ... tadi pagi aku nyiba buka masih bisa tapi sekrang sudah tidak bisa di buka lagi. selalu connecting. Please fix it asap :(

**Comment by gvoze32** [comment]
Sudah si fix ya, silahkan download versi terbaru

**Comment by wildrmdn88** [comment]
yo thank u bruh🙏🏻🙏🏻🙏🏻🙏🏻

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
