### ISSUE TITLE
[BUG] lezhin.com

### ISSUE THREAD

**Issue by apexpredator29** [gvoze32/unblockhostid#507]
masih gini
![bug](https://user-images.githubusercontent.com/41314138/54333210-9ad38600-465c-11e9-91c9-fa32fc3c5185.PNG)

**Comment by gvoze32** [comment]
`.38. to .32.`
`192.0.78.13 social.lezhin.com`
`52.26.69.40 polyfill-io.lezhin.com`

**Comment by gvoze32** [comment]
Else

```
static.dable.io
fs.bizspring.net
cdn.polyfill.io
```

**Comment by apexpredator29** [comment]
> 
> 
> Else
> 
> ```
> static.dable.io
> fs.bizspring.net
> cdn.polyfill.io
> ```

gak pake host?

**Comment by apexpredator29** [comment]
> 
> 
> Else
> 
> ```
> static.dable.io
> fs.bizspring.net
> cdn.polyfill.io
> ```

maksudnya gimana ini, gak pake IP?

**Comment by apexpredator29** [comment]
> 
> 
> Else
> 
> ```
> static.dable.io
> fs.bizspring.net
> cdn.polyfill.io
> ```

maksudnya gimana ini, gak pake IP?

**Comment by gvoze32** [comment]
Tunggu update selanjutnya, masih testing

**Comment by gvoze32** [comment]
```
api.lezhin.com
dondog.lezhin.com
log-scv.lezhin.com
```

**Comment by gvoze32** [comment]
This is new list for lezhin, you can update it manually or wait for the next update

```
216.239.36.21 lezhin.com
52.41.218.23 www.lezhin.com
96.16.173.63 cdn.lezhin.com
192.0.78.13 social.lezhin.com
52.26.69.40 polyfill-io.lezhin.com
52.26.69.40 api.lezhin.com
35.186.216.127 dondog.lezhin.com
35.186.214.176 log-scv.lezhin.com
```

**Comment by apexpredator29** [comment]
thanks for the effort, it worked now
