### ISSUE TITLE
[ID] [BUG] Internet positif

### ISSUE THREAD

**Issue by troke12** [gvoze32/unblockhostid#51]
seperti yang dijudul, semua ip address direct linknya pada gak mau semua, kena internet positif, saya coba pasang di komputer kena internet positif, kemudian coba restart router beberapa kali tetap kena internet positif, nah kemudian saya coba di Laptop, hasilnya juga sama. tolong ip nya di update 
![image](https://user-images.githubusercontent.com/10250068/34075991-8aecf3fa-e313-11e7-8624-bcb5777f508e.png)

**Comment by gvoze32** [comment]
Kalau akses langsung lewat ip/direct ip memang banyak website yang tidak membolehkannya, silahkan akses lewat domain website / www. ya...

**Comment by gvoze32** [comment]
Wah ternyata habis saya cek memang tidak bisa, hmm, mungkin sudah ditutup bugnya... Mungkin ini akhir dari metode ini...

Saya coba cari-cari info dulu mengenai ini dan cara memperbaikinya..

**Comment by gvoze32** [comment]
=FIXED=
Bisa tolong ss folder hosts yang ada di C:\Windows\System32\drivers\etc?

**Comment by gvoze32** [comment]
Coba baca ini untuk lebih lengkapnya, Thanks
https://github.com/gvoze32/unblockhostid/issues/52

**Comment by troke12** [comment]
![image](https://user-images.githubusercontent.com/10250068/34109600-173840fe-e43f-11e7-90c4-fb041fff722d.png)
halo ini saya liat gak ada file host gembok, terus saya sudah coba hapus file hosts dan paste ulang lagi dan coba buka kbagi.com tetap internet positif

**Comment by gvoze32** [comment]
Saya tidak melihat ada hosts.ics disitu, mungkin saja itu penyebabnya

**Comment by troke12** [comment]
harusnya kalau ga ada itu bisa dong, tapi kok ga bisa?

**Comment by gvoze32** [comment]
Coba tambahkan saja, kalau tetep gabisa coba clear semua data browser kemudian restart pc

**Comment by gvoze32** [comment]
Saya dan yang lain lancar aja tuh
