### ISSUE TITLE
[BUG] yomanga.co

### ISSUE THREAD

**Issue by apexpredator29** [gvoze32/unblockhostid#528]
web masih terblokir

**Comment by gvoze32** [comment]
The website is already unblocked but the website is currently error. maybe still maintenance.

So i close this issue for now.

**Comment by apexpredator29** [comment]
but it still redirected to internet positive

**Comment by gvoze32** [comment]
That's weird, mine's not

**Comment by gvoze32** [comment]
Try to flush your dns cache

**Comment by apexpredator29** [comment]
i have done that and nothing changed
