### ISSUE TITLE
[BUG] motherless.com

### ISSUE THREAD

**Issue by anaya77** [gvoze32/unblockhostid#555]
video tidak bisa diplay.

**Comment by gvoze32** [comment]
```
motherlessmedia.com
cdn5-videos.motherlessmedia.com
cdn5-avatars.motherlessmedia.com
```

Wait for the next update

**Comment by kurotennosu** [comment]
ada keniatan untuk donasi tetapi gak tau alamat email nya

**Comment by gvoze32** [comment]
gvoze32@gmail.com

**Comment by kurotennosu** [comment]
Ada minimum donasi nya?

Pada tanggal Min, 7 Apr 2019 05.41 Syafa Adena <notifications@github.com
menulis:

**Comment by gvoze32** [comment]
Tidak ada nominal terserah

**Comment by kurotennosu** [comment]
Minta nomor rekeningnya

Pada tanggal Min, 7 Apr 2019 07.53 Syafa Adena <notifications@github.com
menulis:

> Tidak ada nominal terserah
>

**Comment by gvoze32** [comment]
Bisakah untuk di email saja?

**Comment by kurotennosu** [comment]
Caranya gimana?

Pada tanggal Min, 7 Apr 2019 08.03 Syafa Adena <notifications@github.com
menulis:

> Bisakah untuk di email saja?
>

**Comment by gvoze32** [comment]
Bisa minta kontak email anda? Nanti saya kirimkan pesan.

**Comment by kurotennosu** [comment]
kurotennosu@gmail.com

Pada tanggal Min, 7 Apr 2019 08.09 Syafa Adena <notifications@github.com
menulis:

> Bisa minta kontak email anda? Nanti saya kirimkan pesan.
>
