### ISSUE TITLE
[BUG] xvideos.com

### ISSUE THREAD

**Issue by anaya77** [gvoze32/unblockhostid#559]
web tidak bisa dibuka , sebelumnya normal.

![Screenshot_2019-04-06 Free Porn Videos - XVIDEOS COM](https://user-images.githubusercontent.com/49011347/55672209-90568600-58c2-11e9-98b9-23c88d1560e4.png)

**Comment by trusta77** [comment]
Tempat gw ok kok bro.

**Comment by gvoze32** [comment]
Coba browser lain

**Comment by anaya77** [comment]
sekarang udah normal lagi
