### ISSUE TITLE
[ASK] How to contribute?

### ISSUE THREAD

**Issue by fathonyfath** [gvoze32/unblockhostid#57]
Hi!

Repository-nya keren! Apakah ada cara untuk aku bisa ngebantu nambah listnya terhadap sites yang di block oleh Internet Positif? Gimana caranya? Langkah yang perlu aku lakukan untuk mendapatkan IP address dari sebuah website bagaimana?

Thanks!

**Comment by 0xh3LL0** [comment]
#20 
silahkan pakai IP Lookup

**Comment by gvoze32** [comment]
Saya biasanya cari di unblocksites.co/en/2/unblock/namasitus.com atau di yougetsignal.com/tools/web-sites-on-web-server.

Untuk contribute, silahkan buat pull request, atau bisa langsung menghubungi saya.

**Comment by fathonyfath** [comment]
Thanks!
Aku akan melakukan pull request untuk menambah sites yang belum terlist oleh list ini.
