### ISSUE TITLE
[BUG] netflix.com

### ISSUE THREAD

**Issue by orczero** [gvoze32/unblockhostid#573]
Hallo min .. tadi saya download unblockhostid terus netflix bisa tuh lancar tapi pas beberapa jam kemudia ga bisa dibuka lagi.. saya user indihome tolongin dong minnnn gantenggg

**Comment by gvoze32** [comment]
Duplicate issue https://github.com/gvoze32/unblockhostid/issues/572

**Comment by orczero** [comment]
min tolong eke donggg sedih ga bisa netflixan T_T

**Comment by gvoze32** [comment]
Emergency notes, use this to fix the Netflix's bug:

```
# [NETFLIX.COM]
23.40.252.158 assets.nflxext.com
69.172.200.241 ir.netflix.com
54.192.13.23 media.netflix.com
52.42.228.237 www.netflix.com
34.211.85.116 help.netflix.com
34.210.61.133 jobs.netflix.com
23.40.252.158 codex.nflxext.com
52.11.24.193 netflix.com
52.37.168.202 api-global.netflix.com
52.34.255.169 ichnaea.netflix.com
35.164.147.207 www.netflix.co.id
54.213.182.74 netflix.co.id
```

**Comment by orczero** [comment]
> Emergency notes, use this to fix the Netflix's bug:
> 
> ```
> # [NETFLIX.COM]
> 23.40.252.158 assets.nflxext.com
> 69.172.200.241 ir.netflix.com
> 54.192.13.23 media.netflix.com
> 52.42.228.237 www.netflix.com
> 34.211.85.116 help.netflix.com
> 34.210.61.133 jobs.netflix.com
> 23.40.252.158 codex.nflxext.com
> 52.11.24.193 netflix.com
> 52.37.168.202 api-global.netflix.com
> 52.34.255.169 ichnaea.netflix.com
> 35.164.147.207 www.netflix.co.id
> 54.213.182.74 netflix.co.id
> ```

terima kasih sudah mereplay tapi tetap tidak bisa juga minnn hiks

![netflix bug](https://user-images.githubusercontent.com/49621626/56114470-1a6db100-5f8b-11e9-9b39-134faf6664cc.jpg)

**Comment by gvoze32** [comment]
Restart pc, flush dns, clear cookies cache.

**Comment by orczero** [comment]
gan maap saya udah ikutin semua tapi kok tetep ga bisa ya T_T maap gan ngerepotin

**Comment by gvoze32** [comment]
I'm doing the update guys, please wait

**Comment by orczero** [comment]
> I'm doing the update guys, please wait

ok bossqueee terima kasih banyak ya.. god bless you!

**Comment by gvoze32** [comment]
Fixed

**Comment by orczero** [comment]
jadi aku harus download lagi yg baru apa gimana min?

**Comment by orczero** [comment]
THANK YOU SO MUCH MINNNNNNNNNNNNNNNN! I LOVE YOU UDAH BISAAAAAAAAA....
