### ISSUE TITLE
[BUG] Netflix.com

### ISSUE THREAD

**Issue by rformylastname** [gvoze32/unblockhostid#582]
Halo, mau tanya, ko saya ga bisa akses netflix ya setelah windows update buat windows defender definition yang terbaru? Udah coba ulang step dari unblockhost ampe goodbye dpi-nya, dengan versi modified yang terbaru, netflix masih tidak bisa diakses. Website "take too long to connect" sedangkan kalo via aplikasinya di windows selalu minta sign in tapi ga masuk2. Mohon bantuannya, terima kasih

**Comment by sirzechs753** [comment]
saya juga tiba2 gabisa buka netflix nih gatau sejak kapan, udah coba reinstall goodbyedpi tetep sama

**Comment by bandaidpuppy** [comment]
Ibid. Ga bisa juga udah semingguan. Pakai dnscrypt juga ga bisa

**Comment by rahardianh** [comment]
having the sama issue on PC
