### ISSUE TITLE
[REQ]game.granbluefantasy.jp

### ISSUE THREAD

**Issue by vantovelhiruzen** [gvoze32/unblockhostid#590]
Untuk ketentuan request, silahkan sertakan kode untuk issue yang dibahas dengan:

[REQ] - Untuk yang mau merekomendasikan situs baru untuk di unblock.

[BUG] - Untuk yang mau melaporkan adanya bug di salah satu situs. Wajib melampirkan detail tentang bug tersebut di deskripsi.

Contoh request untuk situs baru: [REQ] example.com

Contoh request untuk bug: [BUG] example.com

Sertakan juga di bagian apa bugnya, misal masih terblokir, gambar tidak muncul, dsb. 

Pastikan website yang akan direquest belum tersedia di list SITES.md:
https://github.com/gvoze32/unblockhostid/blob/master/SITES.md (Gunakan CTRL+F untuk mencari)

Bagi yang request tidak sesuai ketentuan, tidak akan saya kerjakan, terima kasih.

**Comment by vantovelhiruzen** [comment]
Sebenarnya bukan ke block" juga sih tapi bingung aja gitu buat play nya harus pake vpn, aneh.

**Comment by devprojectid** [comment]
bukan region lock kah ?

**Comment by vantovelhiruzen** [comment]
Sepertinya bukan deh, soalnya tmn saya bisa tanpa pake vpn dan 1 provider. Atau iya ya kena region lock bingung sih.

**Comment by devprojectid** [comment]
Soalnya kalau untuk game di indo masih belum terlalu ketat sih, jarang main blokir".
Kemungkinan si region lock

**Comment by vantovelhiruzen** [comment]
![image](https://user-images.githubusercontent.com/41057289/56971091-c241cc00-6b92-11e9-803c-0989d39144af.png)
[](url)
![59318017_281566512791502_5094996252999811072_n](https://user-images.githubusercontent.com/41057289/56971137-e6051200-6b92-11e9-8f30-4bd908296c79.png)

Yang atas punya saya yang bawah punya teman saya.

**Comment by devprojectid** [comment]
beda gan, itu local ip. coba cek public ip disini https://www.whatismyip.com/

**Comment by vantovelhiruzen** [comment]
139.xxx punya saya
118.xxx punya temen saya

**Comment by gvoze32** [comment]
gak keblok di saya
