### ISSUE TITLE
[ID][REQUEST] 

### ISSUE THREAD

**Issue by Kutukertas** [gvoze32/unblockhostid#60]
Gan request buat official android appnya Reddit dong sama Imgur juga :3
Thx b4

**Comment by gvoze32** [comment]
Maksudnya gimana ini gan?

**Comment by Kutukertas** [comment]
Official app Reddit di Android gak bisa
Imgur juga gk bisa

**Comment by gvoze32** [comment]
Mungkin ipnya, nanti saya coba ganti lagi
