### ISSUE TITLE
[BUG] Netflix.com

### ISSUE THREAD

**Issue by rahardianh** [gvoze32/unblockhostid#615]
<img width="1410" alt="Screen Shot 2019-05-16 at 14 35 31" src="https://user-images.githubusercontent.com/50361390/57835134-1f22c080-77e8-11e9-9d5d-8cb8905dc552.png">
able to access netflix.com though the connection speed utterly slow. could not watch any movie since the player was not loaded

**Comment by gvoze32** [comment]
GoodbyeDPI?

**Comment by rahardianh** [comment]
is it available goodbyeDPI on mac tho?

**Comment by vindytr** [comment]
Hey i had the same problem, I installed GoodbyeDPI and the site still slow. I think indihome has a new method to block netflix? because a week ago the site still normal using unblock+goodbyedpi

**Comment by gvoze32** [comment]
@rahardianh 
GoodbyeDPI only available on Windows currently. In inux you can use zapret.

@vindytr 
Try to reinstall GoodbyeDPI and reapply UNBLOCKHOSTID.
