### ISSUE TITLE
[BUG] pornhub.com

### ISSUE THREAD

**Issue by anaya77** [gvoze32/unblockhostid#619]
tampilan web kayak gini , pake vpn baru normal

![Screenshot_2019-05-18 Free Porn Videos Sex Movies - Porno, XXX, Porn Tube Pornhub](https://user-images.githubusercontent.com/49011347/57971291-52b34580-79b6-11e9-9c8e-c4394fcce89a.png)

**Comment by gvoze32** [comment]
Pasti selain indihome ya, kudu pake additional hosts, tapi fiturnya donate
