### ISSUE TITLE
[BUG] AdAway Host Source

### ISSUE THREAD

**Issue by DSanHao** [gvoze32/unblockhostid#624]
AdAway hanya import beberapa entry situs yang ada di host 
``https://raw.githubusercontent.com/gvoze32/unblockhostid/master/hosts``
Sehingga banyak situs yang masih tidak bisa dibuka.
Berikut saya lampirkan file host yang di gunakan oleh AdAway (ekstensi saya ganti untuk memudahkan upload ke github). 
Terima kasih

[hosts.txt](https://github.com/gvoze32/unblockhostid/files/3204899/hosts.txt)

**Comment by gvoze32** [comment]
Sepertinya terkena limit ya
