### ISSUE TITLE
[REQ] FB, Messenger, WA Web, Instagram

### ISSUE THREAD

**Issue by g4r15** [gvoze32/unblockhostid#628]
Facebook (facebook.com)
Facebook Messenger (messenger.com)
Whatsapp WEB (web.whatsapp.com)
Instagram (instagram.com)

Untuk akses dari desktop pc, dan/atau android mobile, saat ini lagi di block sebagian (picture, video) oleh pemerintah. Terima kasih.

**Comment by illvart** [comment]
Silahkan coba [di sini](https://gist.github.com/illvart/3981447c9dcf65e5282d99847a4b9c98).

**Comment by gvoze32** [comment]
Can't do
