### ISSUE TITLE
[BUG] Netflix.com

### ISSUE THREAD

**Issue by exo005** [gvoze32/unblockhostid#639]
Ada bug di bagian Netflix.com, videonya tidak mau play, jadi muter terus tapi gak play sama sekali udah ditungguin 30 menitan, kayak begini https://i.imgur.com/IpfeI6m.jpg
Sejauh ini udah coba gonta ganti pake DNS google maupun DNS lain tetep kayak gitu, udah ngikutin juga cara di Netflix.md (ambil yang Modified) juga kayak gitu, gak mau ke-play.
Padahal koneksinya juga normal : https://www.speedtest.net/result/8297018060.png
Terima kasih.

**Comment by gvoze32** [comment]
Sudah saya fix, bisa update hostsnya lalu download ulang GoodbyeDPI-nya, jangan lupa open filternya dengan cara jalankan file goodbyedpi.exe. Bila tetap tidak bisa, tolong reopen issue ini.

**Comment by exo005** [comment]
Jadi yang saya lakuin : 
1. Download ulang unblock-nya
2. Download ulang GoodbyeDPI
3. Apply Unblock v6.1
4. Run as Administrator "Install_Service.cmd" (Sebelumnya udah di "remove_service.cmd")
5. Run as Administrator "goodbyedpi.exe"
Mohon dikoreksi kalau ada langkah-langkah yang salah...

Awalnya bisa, terus habis ganti episode stuck lagi, coba ke film lain barangkali bisa, ternyata sama aja, stuck lagi : https://i.imgur.com/UbWML6M.jpg
Ganti DNS ke 8.8.8.8 ga bisa, ganti ke 1.1.1.1 juga ga bisa, obtain DNS Server Address Automatically juga ga bisa...

**Comment by gvoze32** [comment]
run services udah?
