### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Blackowl50** [gvoze32/unblockhostid#64]
bang buat beberapa situs kalo di wifi.id kok masih tetp kena inet positif ya ?
sama request ini dong bang http://javhub.net/ sama ini https://www5.javmost.com/

**Comment by gvoze32** [comment]
Punya saya lancar aja tuh, pake hp ya?

**Comment by korzk** [comment]
saya javhub ga bisa kebuka , tapi javmost masi bisa hmm

**Comment by hozzaq** [comment]
@gvoze32 javhub gk ada di host list, kena block di jaringan tri
