### ISSUE TITLE
[BUG] Netflix.com #639

### ISSUE THREAD

**Issue by exo005** [gvoze32/unblockhostid#641]
Jadi yang saya lakuin : 
1. Download ulang unblock-nya
2. Download ulang GoodbyeDPI
3. Apply Unblock v6.1
4. Run as Administrator "Install_Service.cmd" (Sebelumnya udah di "remove_service.cmd")
5. Run as Administrator "goodbyedpi.exe"
Mohon dikoreksi kalau ada langkah-langkah yang salah...

Awalnya bisa, terus habis ganti episode stuck lagi, coba ke film lain barangkali bisa, ternyata sama aja, stuck lagi : https://i.imgur.com/UbWML6M.jpg
Ganti DNS ke 8.8.8.8 ga bisa, ganti ke 1.1.1.1 juga ga bisa, obtain DNS Server Address Automatically juga ga bisa...

_Originally posted by @exo005 in https://github.com/gvoze32/unblockhostid/issues/639#issuecomment-497328689_

**Comment by gvoze32** [comment]
Run services sudah?

**Comment by exo005** [comment]
sudah, tetep stuck, tapi yang lainnya lancar (search film dsb), cuman pas muter videonya aja yang stuck muter terus...
ada urutannya kah yang mana dulu yang harusnya dijalanin, antara Install_service, Run_service, sama goodbyedpi.exe?

**Comment by gvoze32** [comment]
Sudah benar sih, nanti saya cek lagi

**Comment by exo005** [comment]
oke, semoga segera teratasi, semuanya udah lancar padahal, cuman pas play video aja muter terus...

**Comment by vindytr** [comment]
sama nih permasalahannya gabisa play video tapi akses ke netflixnya lancar. udah reapply unblockhost+goodbyedpi juga masih tetep

**Comment by gvoze32** [comment]
Fixed
