### ISSUE TITLE
[BUG] setelah pencet install di aplikasi unblockhostid v6.1

### ISSUE THREAD

**Issue by muhammadidan** [gvoze32/unblockhostid#646]
Setelah pencet tombol install di aplikasi unblockhostid ada tulisan host sukses di install, tapi setelah di tes di browser tetap ada internet positif, terus di menu options yang bisa dipencet hanya restore host. Mohon pencerahannya, Tks

**Comment by gvoze32** [comment]
> Setelah pengaplikasian, tolong lakukan flush dns atau restart pc.

> Fitur lain memang dikhususkan untuk versi donate, terima kasih.
