### ISSUE TITLE
[REQ] player.hanime.tv

### ISSUE THREAD

**Issue by vantovelhiruzen** [gvoze32/unblockhostid#652]
Untuk ketentuan request, silahkan sertakan kode untuk issue yang dibahas dengan:

[REQ] - Untuk yang mau merekomendasikan situs baru untuk di unblock.

[BUG] - Untuk yang mau melaporkan adanya bug di salah satu situs. Wajib melampirkan detail tentang bug tersebut di deskripsi.

Contoh request untuk situs baru: [REQ] example.com

Contoh request untuk bug: [BUG] example.com

Sertakan juga di bagian apa bugnya, misal masih terblokir, gambar tidak muncul, dsb. 

Pastikan website yang akan direquest belum tersedia di list SITES.md:
https://github.com/gvoze32/unblockhostid/blob/master/SITES.md (Gunakan CTRL+F untuk mencari)

Bagi yang request tidak sesuai ketentuan, tidak akan saya kerjakan, terima kasih.

**Comment by vantovelhiruzen** [comment]
![image](https://user-images.githubusercontent.com/41057289/59292065-6e082c80-8ca6-11e9-94c7-16f839348f1f.png)
Ini sebenarnya hanime.tv tetapi waktu di play ke redirect ke player.hanime.tv.

**Comment by dotnauj** [comment]
Tambahin ini ke host gan
```
151.101.65.195 player.hanime.tv
```

**Comment by vantovelhiruzen** [comment]
@dotnauj Makasih gan, dah bisa ke play sekarang.
