### ISSUE TITLE
[ASK] cara install di mac dan nonton netflix.com?

### ISSUE THREAD

**Issue by muhammadidan** [gvoze32/unblockhostid#655]
Cara install di mac os gimana ya? goodbyedpi untuk netflix.com di mac ada ga ya?

**Comment by gvoze32** [comment]
Silahkan lihat https://github.com/gvoze32/unblockhostid/blob/master/NETFLIX.md

**Comment by muhammadidan** [comment]
masih belum berhasil menginstall unblockhostid nya di mac, command pertama katanya permission denied, command yang kedua udah minta pass tapi abis itu ada tulisan command not found. mohon pencerahannya thx

**Comment by gvoze32** [comment]
Bukan pake command, langsung download yang gui saja

https://github.com/SadeghHayeri/GreenTunnel/releases
