### ISSUE TITLE
[REQ] Rule 34 xxx

### ISSUE THREAD

**Issue by Kittysune** [gvoze32/unblockhostid#657]
saat membuka rule 34 xxx nya fine tapi pas memasuki bagian post nggak bisa di load dengan benar seakan ya di blokir 
![image](https://user-images.githubusercontent.com/33630131/59682862-a6a98800-9209-11e9-8ead-929a8e8634f8.png)

**Comment by dotnauj** [comment]
gw bantuin yah..
host Rule34 di timpa aja sama yg ini
```
# [RULE34.XXX]
104.25.223.113 rule34.xxx www.rule34.xxx hk.rule34.xxx img.rule34.xxx
185.180.221.231 webmc.rule34.xxx
89.233.106.186 webm.rule34.xxx
```

**Comment by Kittysune** [comment]
> gw bantuin yah..
> host Rule34 di timpa aja sama yg ini
> 
> ```
> # [RULE34.XXX]
> 104.25.223.113 rule34.xxx www.rule34.xxx hk.rule34.xxx img.rule34.xxx
> 185.180.221.231 webmc.rule34.xxx
> 89.233.106.186 webm.rule34.xxx
> ```

terima kasih
