### ISSUE TITLE
[BUG] hentai-for.me

### ISSUE THREAD

**Issue by RifkyA911** [gvoze32/unblockhostid#662]
Masi kena ipochan
halamannya pas mw jelajah jadi en.hentai-for.me

**Comment by dotnauj** [comment]
tak bantuin
```
# [HENTAI-FOR.ME]
104.31.82.117 hentai-for.me www.hentai-for.me en.hentai-for.me 
```

mending jangan di close dulu biar devnya bisa nambahin ke app
