### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GrumpyJokoBolot** [gvoze32/unblockhostid#709]
Ketentuan request, silahkan sertakan kode untuk issue dengan format:

[REQ] - Untuk yang mau merekomendasikan situs baru untuk di unblock.

[BUG] - Untuk yang mau melaporkan adanya bug di salah satu situs. Lampirkan juga detail bug di deskripsi.

Contoh request untuk situs baru: [REQ] example.com

Contoh request untuk bug: [BUG] example.com

Pastikan website yang akan direquest belum tersedia di list SITES.md:
https://github.com/gvoze32/unblockhostid/blob/master/SITES.md (Gunakan CTRL+F untuk mencari)

Terima kasih sudah berkontribusi dalam pengembangan komunitas aplikasi ini, semoga dapat bermanfaat bagi semua yang memakainya.

**Comment by GrumpyJokoBolot** [comment]
Unhandled exception gas occured in your application.... Access to the path 'C:\Windows\System32\drivers\etc\hosts' is denied. 
How to solve this problem, maybe one or two cent from the expert would help

**Comment by dotnauj** [comment]
Go to "C:\Windows\System32\drivers\etc", Right Click on "hosts" then click properties, and then uncheck "read-only" at "hosts properties attribute"

**Comment by gvoze32** [comment]
Run as administrator or try @dotnauj tips
