### ISSUE TITLE
[EX][BUG] Android host

### ISSUE THREAD

**Issue by fire-fantasy** [gvoze32/unblockhostid#71]
Gak work di Android 5.0 sudah pake non id jga tetap gak work, yang manual maupun pake adaway.

Padahal pake lepi work dengan provider yang sama

**Comment by gvoze32** [comment]
Ada hp lain? Coba jalankan di hp lain, jika work/tidak work, silahkan laporkan ke saya agar bisa saya cari penyebabnya.
