### ISSUE TITLE
[BUG] netflix.com Error (T1-H1-W80072EFD)

### ISSUE THREAD

**Issue by bandaidpuppy** [gvoze32/unblockhostid#711]
Problem communicating with Netflix (T1-H1-W80072EFD)

Sudah saya coba remove service, download Unblockhostid v6.6, re-instal Unblockhostid, dan install service goodbyedpi-0.1.5rc1, masih belum bisa streaming.
Kayaknya unblocker-nya kedetect, yang mana ga dibolehin sama netflix. TY
![Capture](https://user-images.githubusercontent.com/49982785/62843668-33def980-bcee-11e9-9967-6bf1e13dd6a5.JPG)

**Comment by gvoze32** [comment]
GoodbyeDPI lagi error gan, pake alternatif aja
https://github.com/gvoze32/unblockhostid/blob/master/NETFLIX.md#vpn-alternatif

**Comment by bandaidpuppy** [comment]
Sipp makasih
