### ISSUE TITLE
[BUG] reddit android app

### ISSUE THREAD

**Issue by MrFatoni** [gvoze32/unblockhostid#725]
Reddit versi app (android) ada beberapa fitur yg gak bisa
list subdomain lengkap reddit

`ssl.reddit.com
out.reddit.com
gateway.reddit.com
buttons.reddit.com
api.reddit.com
events.reddit.com
amp.reddit.com
strapi.reddit.com
d.reddit.com
np.reddit.com
meta-api.reddit.com
gql.reddit.com
oauth.reddit.com
ads.reddit.com
www.reddit.com
mod.reddit.com
s.reddit.com
bettertouchtool.reddit.com
alb.reddit.com
pixel.reddit.com
old.reddit.com
v21.reddit.com
m.reddit.com
diaperedhentai.reddit.com
abdl.reddit.com
as.reddit.com
i.reddit.com
about.reddit.com
beta.reddit.com
pepetraders.reddit.com
e.reddit.com
so.reddit.com
ps.reddit.com
en.reddit.com
new.reddit.com
thumbs.reddit.com
2fwww.reddit.com
sp.reddit.com
nm.reddit.com
ex.reddit.com
ww.reddit.com
no.reddit.com
h.reddit.com
bitfinex.reddit.com
rhs.reddit.com
sendbird.reddit.com
effectai.reddit.com
toqqn.reddit.com
pectiv.reddit.com
dc.reddit.com
accounts.reddit.com
ud.reddit.com
security.reddit.com
acer.reddit.com
cc.reddit.com
gg.reddit.com
se.reddit.com
habs.reddit.com
4x.reddit.com
origin.reddit.com
ma.reddit.com
eo.reddit.com
loid.reddit.com
es.reddit.com
cx.reddit.com
2fout.reddit.com
ro.reddit.com
news.reddit.com
nl.reddit.com
ol.reddit.com
dd.reddit.com
yogscast.reddit.com
jwww.reddit.com
ja.reddit.com
tr.reddit.com
pay.reddit.com
code.reddit.com
static.reddit.com
2fold.reddit.com
de.reddit.com
initref.reddit.com
auth.reddit.com
22www.reddit.com
v2.reddit.com
blog.reddit.com
bt.reddit.com
st.reddit.com
dreams.reddit.com
srs.reddit.com
rseor3.reddit.com
nsfw.reddit.com
test.reddit.com
edgebucket.reddit.com
token.reddit.com
rabt.reddit.com
pt.reddit.com
sf.reddit.com
us.reddit.com
fr.reddit.com
252fwww.reddit.com`

**Comment by gvoze32** [comment]
Woah mantap gan, nanti langsung digarap
