### ISSUE TITLE
[REQUEST] Adaway fix

### ISSUE THREAD

**Issue by TrixPone** [gvoze32/unblockhostid#76]
Just created an account for this.. 
Mohon maaf utk salah penulisan.. 

Di guide utk Adaway..
Setelah di add url host nya, 

Seharusnya di setting Adaway
Opsi "Allow Redirections" di centang..

Klo tidak, adaway gk akan nambahin url redirection utk file host nya

Thanks :)

**Comment by TrixPone** [comment]
![screenshot_20180114-185657](https://user-images.githubusercontent.com/35420947/34917035-fa2503a6-f97b-11e7-89e5-687b7d0f1843.png)

**Comment by gvoze32** [comment]
Done, terima kasih telah menambahkan fix tersebut.
