### ISSUE TITLE
[ID] [BUG] This connection was reset

### ISSUE THREAD

**Issue by CelloD** [gvoze32/unblockhostid#87]
Gak bisa buka web yg blokir, error "connection was reset" di android

**Comment by CelloD** [comment]
Pake vpn lancar

**Comment by gvoze32** [comment]
Masih kurang tau masalah di android, soalnya hp saya unrooted.

**Comment by CelloD** [comment]
https://www.dropbox.com/s/yevc3lllsr3v784/hosts?dl=0

Ane edit sedikit, hapus bagian awal" trus di merge ke host aslinya... Udah fix pake ini.. Mungkin bisa diliat apa yg salah

**Comment by gvoze32** [comment]
Sip
