### ISSUE TITLE
[ID][BUG] masih banyak yg kena internet positif

### ISSUE THREAD

**Issue by ilhm666** [gvoze32/unblockhostid#93]
pake provider indihome
hitomi.la > harus search via google hitomi la baru bisa akses
hentaihaven.org
javhihi.com
netflix.com dll.
![untitled010101](https://user-images.githubusercontent.com/36272068/36032354-b1587942-0de8-11e8-8dd4-ffb136bf1b9c.jpg)

**Comment by ilhm666** [comment]
![untitled010101](https://user-images.githubusercontent.com/36272068/36032298-82032e3a-0de8-11e8-989a-11d080e2dc39.jpg)

**Comment by gvoze32** [comment]
Memang di mobile agak susah, saya tes juga begitu, tapi pas lewat pc normal langsung bisa diakses. Btw itu pake metode yang mana, hh udah root?

**Comment by lepz0r** [comment]
Buat indihome emang ada DNS di proxy HTTP (Port 80) nya, jadi IPnya diredirect menurut DNS Telkom, solusinya tambahin HTTPS:// di depan domain (biar otomatis Install extension HTTPS Everywhere) / VPN buat situs yg ga support HTTPS

**Comment by ilhm666** [comment]
itu pakai chrome di windows 7, sudah pasang extension HTTPS everywhere juga

**Comment by gvoze32** [comment]
Owh di pc, saya kira andro, bisa coba ss folder drivers/etc di sini?

**Comment by ilhm666** [comment]
![untitled11](https://user-images.githubusercontent.com/36272068/36096688-56f1f6d0-1032-11e8-9ac0-8014a98db522.jpg)

**Comment by gvoze32** [comment]
Mungkin hosts.ics gan, tapi kurang tau juga sih
