### ISSUE TITLE
[BUG] [ID] Can't open Netflix and/or Reddit

### ISSUE THREAD

**Issue by moecantplay** [gvoze32/unblockhostid#97]
can't access both websites.

**Comment by gvoze32** [comment]
![image](https://user-images.githubusercontent.com/28755051/36425592-de088614-1679-11e8-86b7-43350dbe150b.png)

Reddit.com works well, but Netflix got an error, i'll fix it in the next version.

**Comment by moecantplay** [comment]
Hi,


Thanks for responding to this matter.

This is the result I'm getting whenever I try to access Reddit,

and as for Netflix it is unreachable.


[cid:17286096-0d21-46f8-aeea-a7a49a8ece5c]


Regards,

Gervin Sean Miranda.


________________________________

**Comment by gvoze32** [comment]
Try click on ADVANCED and add an exception.

**Comment by gvoze32** [comment]
If still can't, let me ask some question, can you open the another, for example kbagi.com or openload.co? If you can't open the others, i'll try to edit the hosts file to "mac language".

**Comment by moecantplay** [comment]
tried clicking on Advance, no luck there..
I tried adding kbagi.com, and it worked. I also tried adding thepiratebay.org, it lead me to internet positif instead..

**Comment by gvoze32** [comment]
Are you using this step or just copy the hosts file?
https://pastebin.com/raw/dSFs93i2

**Comment by moecantplay** [comment]
yes, i followed that step.. through terminal

**Comment by gvoze32** [comment]
Hmm, maybe you need to flush your dns cache
http://osxdaily.com/2008/03/21/how-to-flush-your-dns-cache-in-mac-os-x/

But i have no idea to fix that, cause i have no mac pc to find the problem

**Comment by moecantplay** [comment]
i already flushed my dns cache using `sudo killall -HUP mDNSResponder` like in the instructions

**Comment by moecantplay** [comment]
hi, any luck yet regarding this issue?

**Comment by gvoze32** [comment]
I have no idea.

**Comment by gvoze32** [comment]
Haven't enough evidence
