### ISSUE TITLE
[BUG] [ID] openload.co

### ISSUE THREAD

**Issue by alilolo123** [gvoze32/unblockhostid#98]
cant access the website/any websites, except the ones that are listed in Non-ID and Safe for Work/only able to access sites in the non-id and safe for work list

**Comment by gvoze32** [comment]
Are you using unrooted mobile phone?

**Comment by alilolo123** [comment]
no, i am using a pc, i have tried all methods of installing and none seem to work..

**Comment by gvoze32** [comment]
Hmm... Still dunno, haven't enough evident

**Comment by alilolo123** [comment]
well, to be more specific, i still get redirected back''internet positive'' when i access ''NFSW'' sites
